/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.ActionField;
import com.SigniFlowup.connect.models.ProxyAllowedField;
import com.SigniFlowup.connect.models.TokenField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddWorkflowStepV2Request
 */
public class AddWorkflowStepV2RequestTest {
    private final AddWorkflowStepV2Request model = new AddWorkflowStepV2Request();

    /**
     * Model tests for AddWorkflowStepV2Request
     */
    @Test
    public void testAddWorkflowStepV2Request() {
        // TODO: test AddWorkflowStepV2Request
    }

    /**
     * Test the property 'actionField'
     */
    @Test
    public void actionFieldTest() {
        // TODO: test actionField
    }

    /**
     * Test the property 'cellField'
     */
    @Test
    public void cellFieldTest() {
        // TODO: test cellField
    }

    /**
     * Test the property 'docIDField'
     */
    @Test
    public void docIDFieldTest() {
        // TODO: test docIDField
    }

    /**
     * Test the property 'emailField'
     */
    @Test
    public void emailFieldTest() {
        // TODO: test emailField
    }

    /**
     * Test the property 'firstNameField'
     */
    @Test
    public void firstNameFieldTest() {
        // TODO: test firstNameField
    }

    /**
     * Test the property 'languageCodeField'
     */
    @Test
    public void languageCodeFieldTest() {
        // TODO: test languageCodeField
    }

    /**
     * Test the property 'lastNameField'
     */
    @Test
    public void lastNameFieldTest() {
        // TODO: test lastNameField
    }

    /**
     * Test the property 'proxyAllowedField'
     */
    @Test
    public void proxyAllowedFieldTest() {
        // TODO: test proxyAllowedField
    }

    /**
     * Test the property 'tokenField'
     */
    @Test
    public void tokenFieldTest() {
        // TODO: test tokenField
    }

}
