/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.AddWokflowStepV2ResponseFlowStepsField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddWokflowStepV2Response
 */
public class AddWokflowStepV2ResponseTest {
    private final AddWokflowStepV2Response model = new AddWokflowStepV2Response();

    /**
     * Model tests for AddWokflowStepV2Response
     */
    @Test
    public void testAddWokflowStepV2Response() {
        // TODO: test AddWokflowStepV2Response
    }

    /**
     * Test the property 'docIDField'
     */
    @Test
    public void docIDFieldTest() {
        // TODO: test docIDField
    }

    /**
     * Test the property 'flowIDField'
     */
    @Test
    public void flowIDFieldTest() {
        // TODO: test flowIDField
    }

    /**
     * Test the property 'flowStepsField'
     */
    @Test
    public void flowStepsFieldTest() {
        // TODO: test flowStepsField
    }

    /**
     * Test the property 'resultField'
     */
    @Test
    public void resultFieldTest() {
        // TODO: test resultField
    }

}
