/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.AutoExpire;
import com.SigniFlowup.connect.models.AutoRemind;
import com.SigniFlowup.connect.models.DocExtension;
import com.SigniFlowup.connect.models.Priority;
import com.SigniFlowup.connect.models.TokenField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateWorkflowRequest
 */
public class CreateWorkflowRequestTest {
    private final CreateWorkflowRequest model = new CreateWorkflowRequest();

    /**
     * Model tests for CreateWorkflowRequest
     */
    @Test
    public void testCreateWorkflowRequest() {
        // TODO: test CreateWorkflowRequest
    }

    /**
     * Test the property 'additionalDataField'
     */
    @Test
    public void additionalDataFieldTest() {
        // TODO: test additionalDataField
    }

    /**
     * Test the property 'autoExpireField'
     */
    @Test
    public void autoExpireFieldTest() {
        // TODO: test autoExpireField
    }

    /**
     * Test the property 'autoRemindField'
     */
    @Test
    public void autoRemindFieldTest() {
        // TODO: test autoRemindField
    }

    /**
     * Test the property 'docField'
     */
    @Test
    public void docFieldTest() {
        // TODO: test docField
    }

    /**
     * Test the property 'docNameField'
     */
    @Test
    public void docNameFieldTest() {
        // TODO: test docNameField
    }

    /**
     * Test the property 'dueDateField'
     */
    @Test
    public void dueDateFieldTest() {
        // TODO: test dueDateField
    }

    /**
     * Test the property 'extensionField'
     */
    @Test
    public void extensionFieldTest() {
        // TODO: test extensionField
    }

    /**
     * Test the property 'messageField'
     */
    @Test
    public void messageFieldTest() {
        // TODO: test messageField
    }

    /**
     * Test the property 'priorityField'
     */
    @Test
    public void priorityFieldTest() {
        // TODO: test priorityField
    }

    /**
     * Test the property 'slAField'
     */
    @Test
    public void slAFieldTest() {
        // TODO: test slAField
    }

    /**
     * Test the property 'tokenField'
     */
    @Test
    public void tokenFieldTest() {
        // TODO: test tokenField
    }

}
