/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DocPrepperAddAdvancedFieldsRequestFieldOptionsListField
 */
public class DocPrepperAddAdvancedFieldsRequestFieldOptionsListFieldTest {
    private final DocPrepperAddAdvancedFieldsRequestFieldOptionsListField model = new DocPrepperAddAdvancedFieldsRequestFieldOptionsListField();

    /**
     * Model tests for DocPrepperAddAdvancedFieldsRequestFieldOptionsListField
     */
    @Test
    public void testDocPrepperAddAdvancedFieldsRequestFieldOptionsListField() {
        // TODO: test DocPrepperAddAdvancedFieldsRequestFieldOptionsListField
    }

    /**
     * Test the property 'linkedValueField'
     */
    @Test
    public void linkedValueFieldTest() {
        // TODO: test linkedValueField
    }

    /**
     * Test the property 'maxField'
     */
    @Test
    public void maxFieldTest() {
        // TODO: test maxField
    }

    /**
     * Test the property 'minField'
     */
    @Test
    public void minFieldTest() {
        // TODO: test minField
    }

    /**
     * Test the property 'valueField'
     */
    @Test
    public void valueFieldTest() {
        // TODO: test valueField
    }

}
