/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField
 */
public class DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListFieldTest {
    private final DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField model = new DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField();

    /**
     * Model tests for DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField
     */
    @Test
    public void testDocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField() {
        // TODO: test DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField
    }

    /**
     * Test the property 'docFieldIDField'
     */
    @Test
    public void docFieldIDFieldTest() {
        // TODO: test docFieldIDField
    }

    /**
     * Test the property 'resultField'
     */
    @Test
    public void resultFieldTest() {
        // TODO: test resultField
    }

}
