/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.AdvancedFieldType;
import com.SigniFlowup.connect.models.DocPrepperAddAdvancedFieldsRequestFieldOptionsListField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DocPrepperAddAdvancedFieldsRequestFieldInfoListField
 */
public class DocPrepperAddAdvancedFieldsRequestFieldInfoListFieldTest {
    private final DocPrepperAddAdvancedFieldsRequestFieldInfoListField model = new DocPrepperAddAdvancedFieldsRequestFieldInfoListField();

    /**
     * Model tests for DocPrepperAddAdvancedFieldsRequestFieldInfoListField
     */
    @Test
    public void testDocPrepperAddAdvancedFieldsRequestFieldInfoListField() {
        // TODO: test DocPrepperAddAdvancedFieldsRequestFieldInfoListField
    }

    /**
     * Test the property 'advancedFieldTypeField'
     */
    @Test
    public void advancedFieldTypeFieldTest() {
        // TODO: test advancedFieldTypeField
    }

    /**
     * Test the property 'docIDField'
     */
    @Test
    public void docIDFieldTest() {
        // TODO: test docIDField
    }

    /**
     * Test the property 'fieldOptionsListField'
     */
    @Test
    public void fieldOptionsListFieldTest() {
        // TODO: test fieldOptionsListField
    }

    /**
     * Test the property 'flowIDField'
     */
    @Test
    public void flowIDFieldTest() {
        // TODO: test flowIDField
    }

    /**
     * Test the property 'fontFamilyField'
     */
    @Test
    public void fontFamilyFieldTest() {
        // TODO: test fontFamilyField
    }

    /**
     * Test the property 'fontSizeField'
     */
    @Test
    public void fontSizeFieldTest() {
        // TODO: test fontSizeField
    }

    /**
     * Test the property 'heightField'
     */
    @Test
    public void heightFieldTest() {
        // TODO: test heightField
    }

    /**
     * Test the property 'widthField'
     */
    @Test
    public void widthFieldTest() {
        // TODO: test widthField
    }

    /**
     * Test the property 'linkToField'
     */
    @Test
    public void linkToFieldTest() {
        // TODO: test linkToField
    }

    /**
     * Test the property 'nameField'
     */
    @Test
    public void nameFieldTest() {
        // TODO: test nameField
    }

    /**
     * Test the property 'pageNumberField'
     */
    @Test
    public void pageNumberFieldTest() {
        // TODO: test pageNumberField
    }

    /**
     * Test the property 'searchableField'
     */
    @Test
    public void searchableFieldTest() {
        // TODO: test searchableField
    }

    /**
     * Test the property 'userEmailField'
     */
    @Test
    public void userEmailFieldTest() {
        // TODO: test userEmailField
    }

    /**
     * Test the property 'valueField'
     */
    @Test
    public void valueFieldTest() {
        // TODO: test valueField
    }

    /**
     * Test the property 'xcoordinateField'
     */
    @Test
    public void xcoordinateFieldTest() {
        // TODO: test xcoordinateField
    }

    /**
     * Test the property 'ycoordinateField'
     */
    @Test
    public void ycoordinateFieldTest() {
        // TODO: test ycoordinateField
    }

}
