/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.FieldType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DocPrepperAddFieldsFlowIDResponse
 */
public class DocPrepperAddFieldsFlowIDResponseTest {
    private final DocPrepperAddFieldsFlowIDResponse model = new DocPrepperAddFieldsFlowIDResponse();

    /**
     * Model tests for DocPrepperAddFieldsFlowIDResponse
     */
    @Test
    public void testDocPrepperAddFieldsFlowIDResponse() {
        // TODO: test DocPrepperAddFieldsFlowIDResponse
    }

    /**
     * Test the property 'docIDField'
     */
    @Test
    public void docIDFieldTest() {
        // TODO: test docIDField
    }

    /**
     * Test the property 'fieldTypeField'
     */
    @Test
    public void fieldTypeFieldTest() {
        // TODO: test fieldTypeField
    }

    /**
     * Test the property 'heightField'
     */
    @Test
    public void heightFieldTest() {
        // TODO: test heightField
    }

    /**
     * Test the property 'pageNumberField'
     */
    @Test
    public void pageNumberFieldTest() {
        // TODO: test pageNumberField
    }

    /**
     * Test the property 'prepperFieldIDField'
     */
    @Test
    public void prepperFieldIDFieldTest() {
        // TODO: test prepperFieldIDField
    }

    /**
     * Test the property 'resultField'
     */
    @Test
    public void resultFieldTest() {
        // TODO: test resultField
    }

    /**
     * Test the property 'userIDField'
     */
    @Test
    public void userIDFieldTest() {
        // TODO: test userIDField
    }

    /**
     * Test the property 'widthField'
     */
    @Test
    public void widthFieldTest() {
        // TODO: test widthField
    }

    /**
     * Test the property 'xcoordinateField'
     */
    @Test
    public void xcoordinateFieldTest() {
        // TODO: test xcoordinateField
    }

    /**
     * Test the property 'ycoordinateField'
     */
    @Test
    public void ycoordinateFieldTest() {
        // TODO: test ycoordinateField
    }

}
