/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.DocPrepperAddAdvancedFieldsRequestFieldInfoListField;
import com.SigniFlowup.connect.models.TokenField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DocPrepperAddAdvancedFieldsRequest
 */
public class DocPrepperAddAdvancedFieldsRequestTest {
    private final DocPrepperAddAdvancedFieldsRequest model = new DocPrepperAddAdvancedFieldsRequest();

    /**
     * Model tests for DocPrepperAddAdvancedFieldsRequest
     */
    @Test
    public void testDocPrepperAddAdvancedFieldsRequest() {
        // TODO: test DocPrepperAddAdvancedFieldsRequest
    }

    /**
     * Test the property 'fieldInfoListField'
     */
    @Test
    public void fieldInfoListFieldTest() {
        // TODO: test fieldInfoListField
    }

    /**
     * Test the property 'tokenField'
     */
    @Test
    public void tokenFieldTest() {
        // TODO: test tokenField
    }

}
