/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.FieldType;
import com.SigniFlowup.connect.models.TokenField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DocPrepperAddFieldsFlowIDRequest
 */
public class DocPrepperAddFieldsFlowIDRequestTest {
    private final DocPrepperAddFieldsFlowIDRequest model = new DocPrepperAddFieldsFlowIDRequest();

    /**
     * Model tests for DocPrepperAddFieldsFlowIDRequest
     */
    @Test
    public void testDocPrepperAddFieldsFlowIDRequest() {
        // TODO: test DocPrepperAddFieldsFlowIDRequest
    }

    /**
     * Test the property 'docFieldTypeField'
     */
    @Test
    public void docFieldTypeFieldTest() {
        // TODO: test docFieldTypeField
    }

    /**
     * Test the property 'docIDField'
     */
    @Test
    public void docIDFieldTest() {
        // TODO: test docIDField
    }

    /**
     * Test the property 'flowIDField'
     */
    @Test
    public void flowIDFieldTest() {
        // TODO: test flowIDField
    }

    /**
     * Test the property 'heightField'
     */
    @Test
    public void heightFieldTest() {
        // TODO: test heightField
    }

    /**
     * Test the property 'widthField'
     */
    @Test
    public void widthFieldTest() {
        // TODO: test widthField
    }

    /**
     * Test the property 'isInvisibleField'
     */
    @Test
    public void isInvisibleFieldTest() {
        // TODO: test isInvisibleField
    }

    /**
     * Test the property 'linkToField'
     */
    @Test
    public void linkToFieldTest() {
        // TODO: test linkToField
    }

    /**
     * Test the property 'pageNumberField'
     */
    @Test
    public void pageNumberFieldTest() {
        // TODO: test pageNumberField
    }

    /**
     * Test the property 'nameField'
     */
    @Test
    public void nameFieldTest() {
        // TODO: test nameField
    }

    /**
     * Test the property 'userEmailField'
     */
    @Test
    public void userEmailFieldTest() {
        // TODO: test userEmailField
    }

    /**
     * Test the property 'xcoordinateField'
     */
    @Test
    public void xcoordinateFieldTest() {
        // TODO: test xcoordinateField
    }

    /**
     * Test the property 'ycoordinateField'
     */
    @Test
    public void ycoordinateFieldTest() {
        // TODO: test ycoordinateField
    }

    /**
     * Test the property 'tokenField'
     */
    @Test
    public void tokenFieldTest() {
        // TODO: test tokenField
    }

}
