/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FullWorkflowRequestWorkflowUserFieldsField
 */
public class FullWorkflowRequestWorkflowUserFieldsFieldTest {
    private final FullWorkflowRequestWorkflowUserFieldsField model = new FullWorkflowRequestWorkflowUserFieldsField();

    /**
     * Model tests for FullWorkflowRequestWorkflowUserFieldsField
     */
    @Test
    public void testFullWorkflowRequestWorkflowUserFieldsField() {
        // TODO: test FullWorkflowRequestWorkflowUserFieldsField
    }

    /**
     * Test the property 'fieldTypeField'
     */
    @Test
    public void fieldTypeFieldTest() {
        // TODO: test fieldTypeField
    }

    /**
     * Test the property 'fontFamilyField'
     */
    @Test
    public void fontFamilyFieldTest() {
        // TODO: test fontFamilyField
    }

    /**
     * Test the property 'fontSizeField'
     */
    @Test
    public void fontSizeFieldTest() {
        // TODO: test fontSizeField
    }

    /**
     * Test the property 'groupUserNumberField'
     */
    @Test
    public void groupUserNumberFieldTest() {
        // TODO: test groupUserNumberField
    }

    /**
     * Test the property 'heightField'
     */
    @Test
    public void heightFieldTest() {
        // TODO: test heightField
    }

    /**
     * Test the property 'isInvisibleField'
     */
    @Test
    public void isInvisibleFieldTest() {
        // TODO: test isInvisibleField
    }

    /**
     * Test the property 'pageNumberField'
     */
    @Test
    public void pageNumberFieldTest() {
        // TODO: test pageNumberField
    }

    /**
     * Test the property 'tagNameField'
     */
    @Test
    public void tagNameFieldTest() {
        // TODO: test tagNameField
    }

    /**
     * Test the property 'valueField'
     */
    @Test
    public void valueFieldTest() {
        // TODO: test valueField
    }

    /**
     * Test the property 'widthField'
     */
    @Test
    public void widthFieldTest() {
        // TODO: test widthField
    }

    /**
     * Test the property 'xcoordinateField'
     */
    @Test
    public void xcoordinateFieldTest() {
        // TODO: test xcoordinateField
    }

    /**
     * Test the property 'xoffsetField'
     */
    @Test
    public void xoffsetFieldTest() {
        // TODO: test xoffsetField
    }

    /**
     * Test the property 'ycoordinateField'
     */
    @Test
    public void ycoordinateFieldTest() {
        // TODO: test ycoordinateField
    }

    /**
     * Test the property 'yoffsetField'
     */
    @Test
    public void yoffsetFieldTest() {
        // TODO: test yoffsetField
    }

}
