/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.AutoRemind;
import com.SigniFlowup.connect.models.DocExtension;
import com.SigniFlowup.connect.models.FullWorkflowRequestPortfolioInformationField;
import com.SigniFlowup.connect.models.FullWorkflowRequestWorkflowUsersListField;
import com.SigniFlowup.connect.models.TokenField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FullWorkflowRequest
 */
public class FullWorkflowRequestTest {
    private final FullWorkflowRequest model = new FullWorkflowRequest();

    /**
     * Model tests for FullWorkflowRequest
     */
    @Test
    public void testFullWorkflowRequest() {
        // TODO: test FullWorkflowRequest
    }

    /**
     * Test the property 'additionalDataField'
     */
    @Test
    public void additionalDataFieldTest() {
        // TODO: test additionalDataField
    }

    /**
     * Test the property 'autoRemindField'
     */
    @Test
    public void autoRemindFieldTest() {
        // TODO: test autoRemindField
    }

    /**
     * Test the property 'customMessageField'
     */
    @Test
    public void customMessageFieldTest() {
        // TODO: test customMessageField
    }

    /**
     * Test the property 'docField'
     */
    @Test
    public void docFieldTest() {
        // TODO: test docField
    }

    /**
     * Test the property 'docNameField'
     */
    @Test
    public void docNameFieldTest() {
        // TODO: test docNameField
    }

    /**
     * Test the property 'dueDateField'
     */
    @Test
    public void dueDateFieldTest() {
        // TODO: test dueDateField
    }

    /**
     * Test the property 'extensionField'
     */
    @Test
    public void extensionFieldTest() {
        // TODO: test extensionField
    }

    /**
     * Test the property 'flattenDocumentField'
     */
    @Test
    public void flattenDocumentFieldTest() {
        // TODO: test flattenDocumentField
    }

    /**
     * Test the property 'keepContentSecurityField'
     */
    @Test
    public void keepContentSecurityFieldTest() {
        // TODO: test keepContentSecurityField
    }

    /**
     * Test the property 'keepCustomPropertiesField'
     */
    @Test
    public void keepCustomPropertiesFieldTest() {
        // TODO: test keepCustomPropertiesField
    }

    /**
     * Test the property 'keepXMPMetadataField'
     */
    @Test
    public void keepXMPMetadataFieldTest() {
        // TODO: test keepXMPMetadataField
    }

    /**
     * Test the property 'portfolioInformationField'
     */
    @Test
    public void portfolioInformationFieldTest() {
        // TODO: test portfolioInformationField
    }

    /**
     * Test the property 'priorityField'
     */
    @Test
    public void priorityFieldTest() {
        // TODO: test priorityField
    }

    /**
     * Test the property 'slAField'
     */
    @Test
    public void slAFieldTest() {
        // TODO: test slAField
    }

    /**
     * Test the property 'sendFirstEmailField'
     */
    @Test
    public void sendFirstEmailFieldTest() {
        // TODO: test sendFirstEmailField
    }

    /**
     * Test the property 'sendWorkflowEmailsField'
     */
    @Test
    public void sendWorkflowEmailsFieldTest() {
        // TODO: test sendWorkflowEmailsField
    }

    /**
     * Test the property 'tokenField'
     */
    @Test
    public void tokenFieldTest() {
        // TODO: test tokenField
    }

    /**
     * Test the property 'workflowUsersListField'
     */
    @Test
    public void workflowUsersListFieldTest() {
        // TODO: test workflowUsersListField
    }

}
