/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FullWorkflowRequestGroupStepFieldGroupMembersField
 */
public class FullWorkflowRequestGroupStepFieldGroupMembersFieldTest {
    private final FullWorkflowRequestGroupStepFieldGroupMembersField model = new FullWorkflowRequestGroupStepFieldGroupMembersField();

    /**
     * Model tests for FullWorkflowRequestGroupStepFieldGroupMembersField
     */
    @Test
    public void testFullWorkflowRequestGroupStepFieldGroupMembersField() {
        // TODO: test FullWorkflowRequestGroupStepFieldGroupMembersField
    }

    /**
     * Test the property 'languageCodeField'
     */
    @Test
    public void languageCodeFieldTest() {
        // TODO: test languageCodeField
    }

    /**
     * Test the property 'userEmailField'
     */
    @Test
    public void userEmailFieldTest() {
        // TODO: test userEmailField
    }

    /**
     * Test the property 'userFullNameField'
     */
    @Test
    public void userFullNameFieldTest() {
        // TODO: test userFullNameField
    }

    /**
     * Test the property 'userMobileNumberField'
     */
    @Test
    public void userMobileNumberFieldTest() {
        // TODO: test userMobileNumberField
    }

}
