/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.FullWorkflowRequestGroupStepFieldGroupMembersField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FullWorkflowRequestGroupStepField
 */
public class FullWorkflowRequestGroupStepFieldTest {
    private final FullWorkflowRequestGroupStepField model = new FullWorkflowRequestGroupStepField();

    /**
     * Model tests for FullWorkflowRequestGroupStepField
     */
    @Test
    public void testFullWorkflowRequestGroupStepField() {
        // TODO: test FullWorkflowRequestGroupStepField
    }

    /**
     * Test the property 'groupMembersField'
     */
    @Test
    public void groupMembersFieldTest() {
        // TODO: test groupMembersField
    }

    /**
     * Test the property 'groupNameField'
     */
    @Test
    public void groupNameFieldTest() {
        // TODO: test groupNameField
    }

    /**
     * Test the property 'requiredNumberOfSignaturesField'
     */
    @Test
    public void requiredNumberOfSignaturesFieldTest() {
        // TODO: test requiredNumberOfSignaturesField
    }

}
