/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FullWorkflowRequestPortfolioInformationField
 */
public class FullWorkflowRequestPortfolioInformationFieldTest {
    private final FullWorkflowRequestPortfolioInformationField model = new FullWorkflowRequestPortfolioInformationField();

    /**
     * Model tests for FullWorkflowRequestPortfolioInformationField
     */
    @Test
    public void testFullWorkflowRequestPortfolioInformationField() {
        // TODO: test FullWorkflowRequestPortfolioInformationField
    }

    /**
     * Test the property 'createPortfolioField'
     */
    @Test
    public void createPortfolioFieldTest() {
        // TODO: test createPortfolioField
    }

    /**
     * Test the property 'linkToPortfolioField'
     */
    @Test
    public void linkToPortfolioFieldTest() {
        // TODO: test linkToPortfolioField
    }

    /**
     * Test the property 'portfolioIDField'
     */
    @Test
    public void portfolioIDFieldTest() {
        // TODO: test portfolioIDField
    }

    /**
     * Test the property 'portfolioNameField'
     */
    @Test
    public void portfolioNameFieldTest() {
        // TODO: test portfolioNameField
    }

}
