/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FullWorkflowResponse
 */
public class FullWorkflowResponseTest {
    private final FullWorkflowResponse model = new FullWorkflowResponse();

    /**
     * Model tests for FullWorkflowResponse
     */
    @Test
    public void testFullWorkflowResponse() {
        // TODO: test FullWorkflowResponse
    }

    /**
     * Test the property 'docField'
     */
    @Test
    public void docFieldTest() {
        // TODO: test docField
    }

    /**
     * Test the property 'docIDField'
     */
    @Test
    public void docIDFieldTest() {
        // TODO: test docIDField
    }

    /**
     * Test the property 'portfolioIDField'
     */
    @Test
    public void portfolioIDFieldTest() {
        // TODO: test portfolioIDField
    }

    /**
     * Test the property 'resultField'
     */
    @Test
    public void resultFieldTest() {
        // TODO: test resultField
    }

    /**
     * Test the property 'statusField'
     */
    @Test
    public void statusFieldTest() {
        // TODO: test statusField
    }

}
