/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetDocumentPrepperLinkResponse
 */
public class GetDocumentPrepperLinkResponseTest {
    private final GetDocumentPrepperLinkResponse model = new GetDocumentPrepperLinkResponse();

    /**
     * Model tests for GetDocumentPrepperLinkResponse
     */
    @Test
    public void testGetDocumentPrepperLinkResponse() {
        // TODO: test GetDocumentPrepperLinkResponse
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'URL'
     */
    @Test
    public void URLTest() {
        // TODO: test URL
    }

}
