/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.TokenField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetDocumentPrepperLinkRequest
 */
public class GetDocumentPrepperLinkRequestTest {
    private final GetDocumentPrepperLinkRequest model = new GetDocumentPrepperLinkRequest();

    /**
     * Model tests for GetDocumentPrepperLinkRequest
     */
    @Test
    public void testGetDocumentPrepperLinkRequest() {
        // TODO: test GetDocumentPrepperLinkRequest
    }

    /**
     * Test the property 'docIDField'
     */
    @Test
    public void docIDFieldTest() {
        // TODO: test docIDField
    }

    /**
     * Test the property 'emailSettingField'
     */
    @Test
    public void emailSettingFieldTest() {
        // TODO: test emailSettingField
    }

    /**
     * Test the property 'returnURLField'
     */
    @Test
    public void returnURLFieldTest() {
        // TODO: test returnURLField
    }

    /**
     * Test the property 'tokenField'
     */
    @Test
    public void tokenFieldTest() {
        // TODO: test tokenField
    }

}
