/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.GetDocumentAuditResponseActivityField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetDocumentAuditResponse
 */
public class GetDocumentAuditResponseTest {
    private final GetDocumentAuditResponse model = new GetDocumentAuditResponse();

    /**
     * Model tests for GetDocumentAuditResponse
     */
    @Test
    public void testGetDocumentAuditResponse() {
        // TODO: test GetDocumentAuditResponse
    }

    /**
     * Test the property 'activityField'
     */
    @Test
    public void activityFieldTest() {
        // TODO: test activityField
    }

    /**
     * Test the property 'resultField'
     */
    @Test
    public void resultFieldTest() {
        // TODO: test resultField
    }

}
