/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.TokenField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetPrepperTemplateListRequest
 */
public class GetPrepperTemplateListRequestTest {
    private final GetPrepperTemplateListRequest model = new GetPrepperTemplateListRequest();

    /**
     * Model tests for GetPrepperTemplateListRequest
     */
    @Test
    public void testGetPrepperTemplateListRequest() {
        // TODO: test GetPrepperTemplateListRequest
    }

    /**
     * Test the property 'templateFolderField'
     */
    @Test
    public void templateFolderFieldTest() {
        // TODO: test templateFolderField
    }

    /**
     * Test the property 'tokenField'
     */
    @Test
    public void tokenFieldTest() {
        // TODO: test tokenField
    }

}
