/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetPrepperTemplateListResponseTemplateInformationValuesField
 */
public class GetPrepperTemplateListResponseTemplateInformationValuesFieldTest {
    private final GetPrepperTemplateListResponseTemplateInformationValuesField model = new GetPrepperTemplateListResponseTemplateInformationValuesField();

    /**
     * Model tests for GetPrepperTemplateListResponseTemplateInformationValuesField
     */
    @Test
    public void testGetPrepperTemplateListResponseTemplateInformationValuesField() {
        // TODO: test GetPrepperTemplateListResponseTemplateInformationValuesField
    }

    /**
     * Test the property 'nameField'
     */
    @Test
    public void nameFieldTest() {
        // TODO: test nameField
    }

    /**
     * Test the property 'prepperTemplateIDField'
     */
    @Test
    public void prepperTemplateIDFieldTest() {
        // TODO: test prepperTemplateIDField
    }

    /**
     * Test the property 'templateDescriptionField'
     */
    @Test
    public void templateDescriptionFieldTest() {
        // TODO: test templateDescriptionField
    }

}
