/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LinkToPortfolioResponse
 */
public class LinkToPortfolioResponseTest {
    private final LinkToPortfolioResponse model = new LinkToPortfolioResponse();

    /**
     * Model tests for LinkToPortfolioResponse
     */
    @Test
    public void testLinkToPortfolioResponse() {
        // TODO: test LinkToPortfolioResponse
    }

    /**
     * Test the property 'portfolioIDField'
     */
    @Test
    public void portfolioIDFieldTest() {
        // TODO: test portfolioIDField
    }

    /**
     * Test the property 'resultField'
     */
    @Test
    public void resultFieldTest() {
        // TODO: test resultField
    }

}
