/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MultipleSignersSigningCeremonyRequestSignerListField
 */
public class MultipleSignersSigningCeremonyRequestSignerListFieldTest {
    private final MultipleSignersSigningCeremonyRequestSignerListField model = new MultipleSignersSigningCeremonyRequestSignerListField();

    /**
     * Model tests for MultipleSignersSigningCeremonyRequestSignerListField
     */
    @Test
    public void testMultipleSignersSigningCeremonyRequestSignerListField() {
        // TODO: test MultipleSignersSigningCeremonyRequestSignerListField
    }

    /**
     * Test the property 'signatureHField'
     */
    @Test
    public void signatureHFieldTest() {
        // TODO: test signatureHField
    }

    /**
     * Test the property 'signatureImageField'
     */
    @Test
    public void signatureImageFieldTest() {
        // TODO: test signatureImageField
    }

    /**
     * Test the property 'signatureImageIncludeBorderField'
     */
    @Test
    public void signatureImageIncludeBorderFieldTest() {
        // TODO: test signatureImageIncludeBorderField
    }

    /**
     * Test the property 'signatureImageIncludeReasonField'
     */
    @Test
    public void signatureImageIncludeReasonFieldTest() {
        // TODO: test signatureImageIncludeReasonField
    }

    /**
     * Test the property 'signatureImageIncludeSignedByField'
     */
    @Test
    public void signatureImageIncludeSignedByFieldTest() {
        // TODO: test signatureImageIncludeSignedByField
    }

    /**
     * Test the property 'signatureImageIncludeSignedDateField'
     */
    @Test
    public void signatureImageIncludeSignedDateFieldTest() {
        // TODO: test signatureImageIncludeSignedDateField
    }

    /**
     * Test the property 'signatureImageTypeField'
     */
    @Test
    public void signatureImageTypeFieldTest() {
        // TODO: test signatureImageTypeField
    }

    /**
     * Test the property 'signaturePageField'
     */
    @Test
    public void signaturePageFieldTest() {
        // TODO: test signaturePageField
    }

    /**
     * Test the property 'signatureWField'
     */
    @Test
    public void signatureWFieldTest() {
        // TODO: test signatureWField
    }

    /**
     * Test the property 'signatureXField'
     */
    @Test
    public void signatureXFieldTest() {
        // TODO: test signatureXField
    }

    /**
     * Test the property 'signatureYField'
     */
    @Test
    public void signatureYFieldTest() {
        // TODO: test signatureYField
    }

    /**
     * Test the property 'signerEmailField'
     */
    @Test
    public void signerEmailFieldTest() {
        // TODO: test signerEmailField
    }

    /**
     * Test the property 'signerFullNameField'
     */
    @Test
    public void signerFullNameFieldTest() {
        // TODO: test signerFullNameField
    }

    /**
     * Test the property 'signerIndentificationNumberField'
     */
    @Test
    public void signerIndentificationNumberFieldTest() {
        // TODO: test signerIndentificationNumberField
    }

    /**
     * Test the property 'signerLocationField'
     */
    @Test
    public void signerLocationFieldTest() {
        // TODO: test signerLocationField
    }

    /**
     * Test the property 'signerMobileNumberField'
     */
    @Test
    public void signerMobileNumberFieldTest() {
        // TODO: test signerMobileNumberField
    }

    /**
     * Test the property 'signerReasonField'
     */
    @Test
    public void signerReasonFieldTest() {
        // TODO: test signerReasonField
    }

    /**
     * Test the property 'signerTrustOriginField'
     */
    @Test
    public void signerTrustOriginFieldTest() {
        // TODO: test signerTrustOriginField
    }

    /**
     * Test the property 'signerTrustReferenceField'
     */
    @Test
    public void signerTrustReferenceFieldTest() {
        // TODO: test signerTrustReferenceField
    }

}
