/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MultipleSignersSigningCeremonyResponse
 */
public class MultipleSignersSigningCeremonyResponseTest {
    private final MultipleSignersSigningCeremonyResponse model = new MultipleSignersSigningCeremonyResponse();

    /**
     * Model tests for MultipleSignersSigningCeremonyResponse
     */
    @Test
    public void testMultipleSignersSigningCeremonyResponse() {
        // TODO: test MultipleSignersSigningCeremonyResponse
    }

    /**
     * Test the property 'ceremonyIDField'
     */
    @Test
    public void ceremonyIDFieldTest() {
        // TODO: test ceremonyIDField
    }

    /**
     * Test the property 'resultField'
     */
    @Test
    public void resultFieldTest() {
        // TODO: test resultField
    }

    /**
     * Test the property 'signedDocumentField'
     */
    @Test
    public void signedDocumentFieldTest() {
        // TODO: test signedDocumentField
    }

}
