/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.MultipleSignersSigningCeremonyRequestSignerListField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MultipleSignersSigningCeremonyRequest
 */
public class MultipleSignersSigningCeremonyRequestTest {
    private final MultipleSignersSigningCeremonyRequest model = new MultipleSignersSigningCeremonyRequest();

    /**
     * Model tests for MultipleSignersSigningCeremonyRequest
     */
    @Test
    public void testMultipleSignersSigningCeremonyRequest() {
        // TODO: test MultipleSignersSigningCeremonyRequest
    }

    /**
     * Test the property 'docField'
     */
    @Test
    public void docFieldTest() {
        // TODO: test docField
    }

    /**
     * Test the property 'docNameField'
     */
    @Test
    public void docNameFieldTest() {
        // TODO: test docNameField
    }

    /**
     * Test the property 'loginPasswordField'
     */
    @Test
    public void loginPasswordFieldTest() {
        // TODO: test loginPasswordField
    }

    /**
     * Test the property 'loginUserNameField'
     */
    @Test
    public void loginUserNameFieldTest() {
        // TODO: test loginUserNameField
    }

    /**
     * Test the property 'signerListField'
     */
    @Test
    public void signerListFieldTest() {
        // TODO: test signerListField
    }

}
