/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.TokenField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SharePortfolioRequest
 */
public class SharePortfolioRequestTest {
    private final SharePortfolioRequest model = new SharePortfolioRequest();

    /**
     * Model tests for SharePortfolioRequest
     */
    @Test
    public void testSharePortfolioRequest() {
        // TODO: test SharePortfolioRequest
    }

    /**
     * Test the property 'accessLevelField'
     */
    @Test
    public void accessLevelFieldTest() {
        // TODO: test accessLevelField
    }

    /**
     * Test the property 'portfolioIDField'
     */
    @Test
    public void portfolioIDFieldTest() {
        // TODO: test portfolioIDField
    }

    /**
     * Test the property 'shareOptionField'
     */
    @Test
    public void shareOptionFieldTest() {
        // TODO: test shareOptionField
    }

    /**
     * Test the property 'tokenField'
     */
    @Test
    public void tokenFieldTest() {
        // TODO: test tokenField
    }

    /**
     * Test the property 'uniqueIDField'
     */
    @Test
    public void uniqueIDFieldTest() {
        // TODO: test uniqueIDField
    }

}
