/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import com.SigniFlowup.connect.models.TokenField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WorkflowSignRequest
 */
public class WorkflowSignRequestTest {
    private final WorkflowSignRequest model = new WorkflowSignRequest();

    /**
     * Model tests for WorkflowSignRequest
     */
    @Test
    public void testWorkflowSignRequest() {
        // TODO: test WorkflowSignRequest
    }

    /**
     * Test the property 'docIDField'
     */
    @Test
    public void docIDFieldTest() {
        // TODO: test docIDField
    }

    /**
     * Test the property 'latitudeField'
     */
    @Test
    public void latitudeFieldTest() {
        // TODO: test latitudeField
    }

    /**
     * Test the property 'loginPasswordField'
     */
    @Test
    public void loginPasswordFieldTest() {
        // TODO: test loginPasswordField
    }

    /**
     * Test the property 'loginUserNameField'
     */
    @Test
    public void loginUserNameFieldTest() {
        // TODO: test loginUserNameField
    }

    /**
     * Test the property 'longitudeField'
     */
    @Test
    public void longitudeFieldTest() {
        // TODO: test longitudeField
    }

    /**
     * Test the property 'signReasonField'
     */
    @Test
    public void signReasonFieldTest() {
        // TODO: test signReasonField
    }

    /**
     * Test the property 'timeZoneOffsetField'
     */
    @Test
    public void timeZoneOffsetFieldTest() {
        // TODO: test timeZoneOffsetField
    }

    /**
     * Test the property 'tokenField'
     */
    @Test
    public void tokenFieldTest() {
        // TODO: test tokenField
    }

}
