/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.SigniFlowup.connect.models.AddWokflowStepV2ResponseFlowStepsField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * #### Add a step to a Workflow response.
 */
@ApiModel(description = "#### Add a step to a Workflow response.")
@JsonPropertyOrder({
  AddWokflowStepV2Response.JSON_PROPERTY_DOC_I_D_FIELD,
  AddWokflowStepV2Response.JSON_PROPERTY_FLOW_I_D_FIELD,
  AddWokflowStepV2Response.JSON_PROPERTY_FLOW_STEPS_FIELD,
  AddWokflowStepV2Response.JSON_PROPERTY_RESULT_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AddWokflowStepV2Response {
  public static final String JSON_PROPERTY_DOC_I_D_FIELD = "DocIDField";
  private BigDecimal docIDField;

  public static final String JSON_PROPERTY_FLOW_I_D_FIELD = "FlowIDField";
  private BigDecimal flowIDField;

  public static final String JSON_PROPERTY_FLOW_STEPS_FIELD = "FlowStepsField";
  private Set<AddWokflowStepV2ResponseFlowStepsField> flowStepsField = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_RESULT_FIELD = "ResultField";
  private String resultField;


  public AddWokflowStepV2Response docIDField(BigDecimal docIDField) {
    this.docIDField = docIDField;
    return this;
  }

   /**
   * Document ID field.
   * @return docIDField
  **/
  @ApiModelProperty(example = "2147483647", required = true, value = "Document ID field.")
  @JsonProperty(JSON_PROPERTY_DOC_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getDocIDField() {
    return docIDField;
  }


  public void setDocIDField(BigDecimal docIDField) {
    this.docIDField = docIDField;
  }


  public AddWokflowStepV2Response flowIDField(BigDecimal flowIDField) {
    this.flowIDField = flowIDField;
    return this;
  }

   /**
   * Document flow ID field
   * @return flowIDField
  **/
  @ApiModelProperty(example = "1111112", required = true, value = "Document flow ID field")
  @JsonProperty(JSON_PROPERTY_FLOW_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getFlowIDField() {
    return flowIDField;
  }


  public void setFlowIDField(BigDecimal flowIDField) {
    this.flowIDField = flowIDField;
  }


  public AddWokflowStepV2Response flowStepsField(Set<AddWokflowStepV2ResponseFlowStepsField> flowStepsField) {
    this.flowStepsField = flowStepsField;
    return this;
  }

  public AddWokflowStepV2Response addFlowStepsFieldItem(AddWokflowStepV2ResponseFlowStepsField flowStepsFieldItem) {
    this.flowStepsField.add(flowStepsFieldItem);
    return this;
  }

   /**
   * Get flowStepsField
   * @return flowStepsField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FLOW_STEPS_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Set<AddWokflowStepV2ResponseFlowStepsField> getFlowStepsField() {
    return flowStepsField;
  }


  public void setFlowStepsField(Set<AddWokflowStepV2ResponseFlowStepsField> flowStepsField) {
    this.flowStepsField = flowStepsField;
  }


  public AddWokflowStepV2Response resultField(String resultField) {
    this.resultField = resultField;
    return this;
  }

   /**
   * Displays the result of the call.
   * @return resultField
  **/
  @ApiModelProperty(example = "success", required = true, value = "Displays the result of the call.")
  @JsonProperty(JSON_PROPERTY_RESULT_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResultField() {
    return resultField;
  }


  public void setResultField(String resultField) {
    this.resultField = resultField;
  }


  /**
   * Return true if this AddWokflowStepV2Response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddWokflowStepV2Response addWokflowStepV2Response = (AddWokflowStepV2Response) o;
    return Objects.equals(this.docIDField, addWokflowStepV2Response.docIDField) &&
        Objects.equals(this.flowIDField, addWokflowStepV2Response.flowIDField) &&
        Objects.equals(this.flowStepsField, addWokflowStepV2Response.flowStepsField) &&
        Objects.equals(this.resultField, addWokflowStepV2Response.resultField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docIDField, flowIDField, flowStepsField, resultField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddWokflowStepV2Response {\n");
    sb.append("    docIDField: ").append(toIndentedString(docIDField)).append("\n");
    sb.append("    flowIDField: ").append(toIndentedString(flowIDField)).append("\n");
    sb.append("    flowStepsField: ").append(toIndentedString(flowStepsField)).append("\n");
    sb.append("    resultField: ").append(toIndentedString(resultField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

