/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * DocPrepperAddAdvancedFieldsRequestFieldOptionsListField
 */
@JsonPropertyOrder({
  DocPrepperAddAdvancedFieldsRequestFieldOptionsListField.JSON_PROPERTY_LINKED_VALUE_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldOptionsListField.JSON_PROPERTY_MAX_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldOptionsListField.JSON_PROPERTY_MIN_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldOptionsListField.JSON_PROPERTY_VALUE_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DocPrepperAddAdvancedFieldsRequestFieldOptionsListField {
  public static final String JSON_PROPERTY_LINKED_VALUE_FIELD = "LinkedValueField";
  private String linkedValueField;

  public static final String JSON_PROPERTY_MAX_FIELD = "MaxField";
  private BigDecimal maxField;

  public static final String JSON_PROPERTY_MIN_FIELD = "MinField";
  private BigDecimal minField;

  public static final String JSON_PROPERTY_VALUE_FIELD = "ValueField";
  private String valueField;


  public DocPrepperAddAdvancedFieldsRequestFieldOptionsListField linkedValueField(String linkedValueField) {
    this.linkedValueField = linkedValueField;
    return this;
  }

   /**
   * Get linkedValueField
   * @return linkedValueField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LINKED_VALUE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLinkedValueField() {
    return linkedValueField;
  }


  public void setLinkedValueField(String linkedValueField) {
    this.linkedValueField = linkedValueField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldOptionsListField maxField(BigDecimal maxField) {
    this.maxField = maxField;
    return this;
  }

   /**
   * Max amount field.
   * @return maxField
  **/
  @ApiModelProperty(example = "5", required = true, value = "Max amount field.")
  @JsonProperty(JSON_PROPERTY_MAX_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getMaxField() {
    return maxField;
  }


  public void setMaxField(BigDecimal maxField) {
    this.maxField = maxField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldOptionsListField minField(BigDecimal minField) {
    this.minField = minField;
    return this;
  }

   /**
   * Min amount field
   * @return minField
  **/
  @ApiModelProperty(example = "2", required = true, value = "Min amount field")
  @JsonProperty(JSON_PROPERTY_MIN_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getMinField() {
    return minField;
  }


  public void setMinField(BigDecimal minField) {
    this.minField = minField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldOptionsListField valueField(String valueField) {
    this.valueField = valueField;
    return this;
  }

   /**
   * Get valueField
   * @return valueField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VALUE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getValueField() {
    return valueField;
  }


  public void setValueField(String valueField) {
    this.valueField = valueField;
  }


  /**
   * Return true if this DocPrepperAddAdvancedFieldsRequest_FieldOptionsListField object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocPrepperAddAdvancedFieldsRequestFieldOptionsListField docPrepperAddAdvancedFieldsRequestFieldOptionsListField = (DocPrepperAddAdvancedFieldsRequestFieldOptionsListField) o;
    return Objects.equals(this.linkedValueField, docPrepperAddAdvancedFieldsRequestFieldOptionsListField.linkedValueField) &&
        Objects.equals(this.maxField, docPrepperAddAdvancedFieldsRequestFieldOptionsListField.maxField) &&
        Objects.equals(this.minField, docPrepperAddAdvancedFieldsRequestFieldOptionsListField.minField) &&
        Objects.equals(this.valueField, docPrepperAddAdvancedFieldsRequestFieldOptionsListField.valueField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkedValueField, maxField, minField, valueField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocPrepperAddAdvancedFieldsRequestFieldOptionsListField {\n");
    sb.append("    linkedValueField: ").append(toIndentedString(linkedValueField)).append("\n");
    sb.append("    maxField: ").append(toIndentedString(maxField)).append("\n");
    sb.append("    minField: ").append(toIndentedString(minField)).append("\n");
    sb.append("    valueField: ").append(toIndentedString(valueField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

