/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.SigniFlowup.connect.models.AdvancedFieldType;
import com.SigniFlowup.connect.models.DocPrepperAddAdvancedFieldsRequestFieldOptionsListField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * DocPrepperAddAdvancedFieldsRequestFieldInfoListField
 */
@JsonPropertyOrder({
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_ADVANCED_FIELD_TYPE_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_DOC_I_D_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_FIELD_OPTIONS_LIST_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_FLOW_I_D_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_FONT_FAMILY_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_FONT_SIZE_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_HEIGHT_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_WIDTH_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_LINK_TO_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_NAME_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_PAGE_NUMBER_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_SEARCHABLE_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_USER_EMAIL_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_VALUE_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_XCOORDINATE_FIELD,
  DocPrepperAddAdvancedFieldsRequestFieldInfoListField.JSON_PROPERTY_YCOORDINATE_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DocPrepperAddAdvancedFieldsRequestFieldInfoListField {
  public static final String JSON_PROPERTY_ADVANCED_FIELD_TYPE_FIELD = "AdvancedFieldTypeField";
  private AdvancedFieldType advancedFieldTypeField;

  public static final String JSON_PROPERTY_DOC_I_D_FIELD = "DocIDField";
  private BigDecimal docIDField;

  public static final String JSON_PROPERTY_FIELD_OPTIONS_LIST_FIELD = "FieldOptionsListField";
  private Set<DocPrepperAddAdvancedFieldsRequestFieldOptionsListField> fieldOptionsListField = null;

  public static final String JSON_PROPERTY_FLOW_I_D_FIELD = "FlowIDField";
  private BigDecimal flowIDField;

  public static final String JSON_PROPERTY_FONT_FAMILY_FIELD = "FontFamilyField";
  private String fontFamilyField;

  public static final String JSON_PROPERTY_FONT_SIZE_FIELD = "FontSizeField";
  private BigDecimal fontSizeField;

  public static final String JSON_PROPERTY_HEIGHT_FIELD = "HeightField";
  private String heightField;

  public static final String JSON_PROPERTY_WIDTH_FIELD = "WidthField";
  private String widthField;

  public static final String JSON_PROPERTY_LINK_TO_FIELD = "LinkToField";
  private String linkToField;

  public static final String JSON_PROPERTY_NAME_FIELD = "NameField";
  private String nameField;

  public static final String JSON_PROPERTY_PAGE_NUMBER_FIELD = "PageNumberField";
  private BigDecimal pageNumberField;

  public static final String JSON_PROPERTY_SEARCHABLE_FIELD = "SearchableField";
  private Boolean searchableField;

  public static final String JSON_PROPERTY_USER_EMAIL_FIELD = "UserEmailField";
  private String userEmailField;

  public static final String JSON_PROPERTY_VALUE_FIELD = "ValueField";
  private String valueField;

  public static final String JSON_PROPERTY_XCOORDINATE_FIELD = "XCoordinateField";
  private String xcoordinateField;

  public static final String JSON_PROPERTY_YCOORDINATE_FIELD = "YCoordinateField";
  private String ycoordinateField;


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField advancedFieldTypeField(AdvancedFieldType advancedFieldTypeField) {
    this.advancedFieldTypeField = advancedFieldTypeField;
    return this;
  }

   /**
   * Get advancedFieldTypeField
   * @return advancedFieldTypeField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ADVANCED_FIELD_TYPE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AdvancedFieldType getAdvancedFieldTypeField() {
    return advancedFieldTypeField;
  }


  public void setAdvancedFieldTypeField(AdvancedFieldType advancedFieldTypeField) {
    this.advancedFieldTypeField = advancedFieldTypeField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField docIDField(BigDecimal docIDField) {
    this.docIDField = docIDField;
    return this;
  }

   /**
   * Document ID field.
   * @return docIDField
  **/
  @ApiModelProperty(example = "2147483647", required = true, value = "Document ID field.")
  @JsonProperty(JSON_PROPERTY_DOC_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getDocIDField() {
    return docIDField;
  }


  public void setDocIDField(BigDecimal docIDField) {
    this.docIDField = docIDField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField fieldOptionsListField(Set<DocPrepperAddAdvancedFieldsRequestFieldOptionsListField> fieldOptionsListField) {
    this.fieldOptionsListField = fieldOptionsListField;
    return this;
  }

  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField addFieldOptionsListFieldItem(DocPrepperAddAdvancedFieldsRequestFieldOptionsListField fieldOptionsListFieldItem) {
    if (this.fieldOptionsListField == null) {
      this.fieldOptionsListField = new LinkedHashSet<>();
    }
    this.fieldOptionsListField.add(fieldOptionsListFieldItem);
    return this;
  }

   /**
   * Get fieldOptionsListField
   * @return fieldOptionsListField
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FIELD_OPTIONS_LIST_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<DocPrepperAddAdvancedFieldsRequestFieldOptionsListField> getFieldOptionsListField() {
    return fieldOptionsListField;
  }


  public void setFieldOptionsListField(Set<DocPrepperAddAdvancedFieldsRequestFieldOptionsListField> fieldOptionsListField) {
    this.fieldOptionsListField = fieldOptionsListField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField flowIDField(BigDecimal flowIDField) {
    this.flowIDField = flowIDField;
    return this;
  }

   /**
   * Document Flow ID field.
   * @return flowIDField
  **/
  @ApiModelProperty(example = "11111", required = true, value = "Document Flow ID field.")
  @JsonProperty(JSON_PROPERTY_FLOW_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getFlowIDField() {
    return flowIDField;
  }


  public void setFlowIDField(BigDecimal flowIDField) {
    this.flowIDField = flowIDField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField fontFamilyField(String fontFamilyField) {
    this.fontFamilyField = fontFamilyField;
    return this;
  }

   /**
   * Font family of the text in the field
   * @return fontFamilyField
  **/
  @ApiModelProperty(example = "Arial", required = true, value = "Font family of the text in the field")
  @JsonProperty(JSON_PROPERTY_FONT_FAMILY_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFontFamilyField() {
    return fontFamilyField;
  }


  public void setFontFamilyField(String fontFamilyField) {
    this.fontFamilyField = fontFamilyField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField fontSizeField(BigDecimal fontSizeField) {
    this.fontSizeField = fontSizeField;
    return this;
  }

   /**
   * Font size of the text in the field
   * @return fontSizeField
  **/
  @ApiModelProperty(example = "12", required = true, value = "Font size of the text in the field")
  @JsonProperty(JSON_PROPERTY_FONT_SIZE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getFontSizeField() {
    return fontSizeField;
  }


  public void setFontSizeField(BigDecimal fontSizeField) {
    this.fontSizeField = fontSizeField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField heightField(String heightField) {
    this.heightField = heightField;
    return this;
  }

   /**
   * Field height
   * @return heightField
  **/
  @ApiModelProperty(example = "30", required = true, value = "Field height")
  @JsonProperty(JSON_PROPERTY_HEIGHT_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHeightField() {
    return heightField;
  }


  public void setHeightField(String heightField) {
    this.heightField = heightField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField widthField(String widthField) {
    this.widthField = widthField;
    return this;
  }

   /**
   * Field Width
   * @return widthField
  **/
  @ApiModelProperty(example = "15", required = true, value = "Field Width")
  @JsonProperty(JSON_PROPERTY_WIDTH_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWidthField() {
    return widthField;
  }


  public void setWidthField(String widthField) {
    this.widthField = widthField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField linkToField(String linkToField) {
    this.linkToField = linkToField;
    return this;
  }

   /**
   * Get linkToField
   * @return linkToField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LINK_TO_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLinkToField() {
    return linkToField;
  }


  public void setLinkToField(String linkToField) {
    this.linkToField = linkToField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField nameField(String nameField) {
    this.nameField = nameField;
    return this;
  }

   /**
   * Get nameField
   * @return nameField
  **/
  @ApiModelProperty(example = "Text Field", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NAME_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNameField() {
    return nameField;
  }


  public void setNameField(String nameField) {
    this.nameField = nameField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField pageNumberField(BigDecimal pageNumberField) {
    this.pageNumberField = pageNumberField;
    return this;
  }

   /**
   * Field page number.
   * @return pageNumberField
  **/
  @ApiModelProperty(example = "2", required = true, value = "Field page number.")
  @JsonProperty(JSON_PROPERTY_PAGE_NUMBER_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getPageNumberField() {
    return pageNumberField;
  }


  public void setPageNumberField(BigDecimal pageNumberField) {
    this.pageNumberField = pageNumberField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField searchableField(Boolean searchableField) {
    this.searchableField = searchableField;
    return this;
  }

   /**
   * Get searchableField
   * @return searchableField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SEARCHABLE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getSearchableField() {
    return searchableField;
  }


  public void setSearchableField(Boolean searchableField) {
    this.searchableField = searchableField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField userEmailField(String userEmailField) {
    this.userEmailField = userEmailField;
    return this;
  }

   /**
   * User email address.
   * @return userEmailField
  **/
  @ApiModelProperty(example = "John@domain.com", required = true, value = "User email address.")
  @JsonProperty(JSON_PROPERTY_USER_EMAIL_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserEmailField() {
    return userEmailField;
  }


  public void setUserEmailField(String userEmailField) {
    this.userEmailField = userEmailField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField valueField(String valueField) {
    this.valueField = valueField;
    return this;
  }

   /**
   * Get valueField
   * @return valueField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VALUE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getValueField() {
    return valueField;
  }


  public void setValueField(String valueField) {
    this.valueField = valueField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField xcoordinateField(String xcoordinateField) {
    this.xcoordinateField = xcoordinateField;
    return this;
  }

   /**
   * X-coordinates of field on the page
   * @return xcoordinateField
  **/
  @ApiModelProperty(example = "60", required = true, value = "X-coordinates of field on the page")
  @JsonProperty(JSON_PROPERTY_XCOORDINATE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getXcoordinateField() {
    return xcoordinateField;
  }


  public void setXcoordinateField(String xcoordinateField) {
    this.xcoordinateField = xcoordinateField;
  }


  public DocPrepperAddAdvancedFieldsRequestFieldInfoListField ycoordinateField(String ycoordinateField) {
    this.ycoordinateField = ycoordinateField;
    return this;
  }

   /**
   * Y-coordinates of field on the page
   * @return ycoordinateField
  **/
  @ApiModelProperty(example = "120", required = true, value = "Y-coordinates of field on the page")
  @JsonProperty(JSON_PROPERTY_YCOORDINATE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getYcoordinateField() {
    return ycoordinateField;
  }


  public void setYcoordinateField(String ycoordinateField) {
    this.ycoordinateField = ycoordinateField;
  }


  /**
   * Return true if this DocPrepperAddAdvancedFieldsRequest_FieldInfoListField object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocPrepperAddAdvancedFieldsRequestFieldInfoListField docPrepperAddAdvancedFieldsRequestFieldInfoListField = (DocPrepperAddAdvancedFieldsRequestFieldInfoListField) o;
    return Objects.equals(this.advancedFieldTypeField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.advancedFieldTypeField) &&
        Objects.equals(this.docIDField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.docIDField) &&
        Objects.equals(this.fieldOptionsListField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.fieldOptionsListField) &&
        Objects.equals(this.flowIDField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.flowIDField) &&
        Objects.equals(this.fontFamilyField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.fontFamilyField) &&
        Objects.equals(this.fontSizeField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.fontSizeField) &&
        Objects.equals(this.heightField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.heightField) &&
        Objects.equals(this.widthField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.widthField) &&
        Objects.equals(this.linkToField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.linkToField) &&
        Objects.equals(this.nameField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.nameField) &&
        Objects.equals(this.pageNumberField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.pageNumberField) &&
        Objects.equals(this.searchableField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.searchableField) &&
        Objects.equals(this.userEmailField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.userEmailField) &&
        Objects.equals(this.valueField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.valueField) &&
        Objects.equals(this.xcoordinateField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.xcoordinateField) &&
        Objects.equals(this.ycoordinateField, docPrepperAddAdvancedFieldsRequestFieldInfoListField.ycoordinateField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(advancedFieldTypeField, docIDField, fieldOptionsListField, flowIDField, fontFamilyField, fontSizeField, heightField, widthField, linkToField, nameField, pageNumberField, searchableField, userEmailField, valueField, xcoordinateField, ycoordinateField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocPrepperAddAdvancedFieldsRequestFieldInfoListField {\n");
    sb.append("    advancedFieldTypeField: ").append(toIndentedString(advancedFieldTypeField)).append("\n");
    sb.append("    docIDField: ").append(toIndentedString(docIDField)).append("\n");
    sb.append("    fieldOptionsListField: ").append(toIndentedString(fieldOptionsListField)).append("\n");
    sb.append("    flowIDField: ").append(toIndentedString(flowIDField)).append("\n");
    sb.append("    fontFamilyField: ").append(toIndentedString(fontFamilyField)).append("\n");
    sb.append("    fontSizeField: ").append(toIndentedString(fontSizeField)).append("\n");
    sb.append("    heightField: ").append(toIndentedString(heightField)).append("\n");
    sb.append("    widthField: ").append(toIndentedString(widthField)).append("\n");
    sb.append("    linkToField: ").append(toIndentedString(linkToField)).append("\n");
    sb.append("    nameField: ").append(toIndentedString(nameField)).append("\n");
    sb.append("    pageNumberField: ").append(toIndentedString(pageNumberField)).append("\n");
    sb.append("    searchableField: ").append(toIndentedString(searchableField)).append("\n");
    sb.append("    userEmailField: ").append(toIndentedString(userEmailField)).append("\n");
    sb.append("    valueField: ").append(toIndentedString(valueField)).append("\n");
    sb.append("    xcoordinateField: ").append(toIndentedString(xcoordinateField)).append("\n");
    sb.append("    ycoordinateField: ").append(toIndentedString(ycoordinateField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

