/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * #### The response returned when a user wants to download a portfolio.
 */
@ApiModel(description = "#### The response returned when a user wants to download a portfolio.")
@JsonPropertyOrder({
  DownloadPortfolioResponse.JSON_PROPERTY_PORTFOLIO_DATA_FIELD,
  DownloadPortfolioResponse.JSON_PROPERTY_PORTFOLIO_I_D_FIELD,
  DownloadPortfolioResponse.JSON_PROPERTY_PORTFOLIO_NAME_FIELD,
  DownloadPortfolioResponse.JSON_PROPERTY_RESULT_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DownloadPortfolioResponse {
  public static final String JSON_PROPERTY_PORTFOLIO_DATA_FIELD = "PortfolioDataField";
  private String portfolioDataField;

  public static final String JSON_PROPERTY_PORTFOLIO_I_D_FIELD = "PortfolioIDField";
  private BigDecimal portfolioIDField;

  public static final String JSON_PROPERTY_PORTFOLIO_NAME_FIELD = "PortfolioNameField";
  private String portfolioNameField;

  public static final String JSON_PROPERTY_RESULT_FIELD = "ResultField";
  private String resultField;


  public DownloadPortfolioResponse portfolioDataField(String portfolioDataField) {
    this.portfolioDataField = portfolioDataField;
    return this;
  }

   /**
   * Portfolio data field.
   * @return portfolioDataField
  **/
  @ApiModelProperty(required = true, value = "Portfolio data field.")
  @JsonProperty(JSON_PROPERTY_PORTFOLIO_DATA_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPortfolioDataField() {
    return portfolioDataField;
  }


  public void setPortfolioDataField(String portfolioDataField) {
    this.portfolioDataField = portfolioDataField;
  }


  public DownloadPortfolioResponse portfolioIDField(BigDecimal portfolioIDField) {
    this.portfolioIDField = portfolioIDField;
    return this;
  }

   /**
   * Portfolio ID.
   * @return portfolioIDField
  **/
  @ApiModelProperty(example = "11112", required = true, value = "Portfolio ID.")
  @JsonProperty(JSON_PROPERTY_PORTFOLIO_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getPortfolioIDField() {
    return portfolioIDField;
  }


  public void setPortfolioIDField(BigDecimal portfolioIDField) {
    this.portfolioIDField = portfolioIDField;
  }


  public DownloadPortfolioResponse portfolioNameField(String portfolioNameField) {
    this.portfolioNameField = portfolioNameField;
    return this;
  }

   /**
   * Portfolio name.
   * @return portfolioNameField
  **/
  @ApiModelProperty(example = "Application Portfolio", required = true, value = "Portfolio name.")
  @JsonProperty(JSON_PROPERTY_PORTFOLIO_NAME_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPortfolioNameField() {
    return portfolioNameField;
  }


  public void setPortfolioNameField(String portfolioNameField) {
    this.portfolioNameField = portfolioNameField;
  }


  public DownloadPortfolioResponse resultField(String resultField) {
    this.resultField = resultField;
    return this;
  }

   /**
   * Displays the result of the call.
   * @return resultField
  **/
  @ApiModelProperty(required = true, value = "Displays the result of the call.")
  @JsonProperty(JSON_PROPERTY_RESULT_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResultField() {
    return resultField;
  }


  public void setResultField(String resultField) {
    this.resultField = resultField;
  }


  /**
   * Return true if this DownloadPortfolioResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DownloadPortfolioResponse downloadPortfolioResponse = (DownloadPortfolioResponse) o;
    return Objects.equals(this.portfolioDataField, downloadPortfolioResponse.portfolioDataField) &&
        Objects.equals(this.portfolioIDField, downloadPortfolioResponse.portfolioIDField) &&
        Objects.equals(this.portfolioNameField, downloadPortfolioResponse.portfolioNameField) &&
        Objects.equals(this.resultField, downloadPortfolioResponse.resultField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(portfolioDataField, portfolioIDField, portfolioNameField, resultField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DownloadPortfolioResponse {\n");
    sb.append("    portfolioDataField: ").append(toIndentedString(portfolioDataField)).append("\n");
    sb.append("    portfolioIDField: ").append(toIndentedString(portfolioIDField)).append("\n");
    sb.append("    portfolioNameField: ").append(toIndentedString(portfolioNameField)).append("\n");
    sb.append("    resultField: ").append(toIndentedString(resultField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

