/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * Portfolio information.
 */
@ApiModel(description = "Portfolio information.")
@JsonPropertyOrder({
  FullWorkflowRequestPortfolioInformationField.JSON_PROPERTY_CREATE_PORTFOLIO_FIELD,
  FullWorkflowRequestPortfolioInformationField.JSON_PROPERTY_LINK_TO_PORTFOLIO_FIELD,
  FullWorkflowRequestPortfolioInformationField.JSON_PROPERTY_PORTFOLIO_I_D_FIELD,
  FullWorkflowRequestPortfolioInformationField.JSON_PROPERTY_PORTFOLIO_NAME_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FullWorkflowRequestPortfolioInformationField {
  public static final String JSON_PROPERTY_CREATE_PORTFOLIO_FIELD = "CreatePortfolioField";
  private Boolean createPortfolioField;

  public static final String JSON_PROPERTY_LINK_TO_PORTFOLIO_FIELD = "LinkToPortfolioField";
  private Boolean linkToPortfolioField;

  public static final String JSON_PROPERTY_PORTFOLIO_I_D_FIELD = "PortfolioIDField";
  private BigDecimal portfolioIDField;

  public static final String JSON_PROPERTY_PORTFOLIO_NAME_FIELD = "PortfolioNameField";
  private String portfolioNameField;


  public FullWorkflowRequestPortfolioInformationField createPortfolioField(Boolean createPortfolioField) {
    this.createPortfolioField = createPortfolioField;
    return this;
  }

   /**
   * Create portfolio.
   * @return createPortfolioField
  **/
  @ApiModelProperty(required = true, value = "Create portfolio.")
  @JsonProperty(JSON_PROPERTY_CREATE_PORTFOLIO_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getCreatePortfolioField() {
    return createPortfolioField;
  }


  public void setCreatePortfolioField(Boolean createPortfolioField) {
    this.createPortfolioField = createPortfolioField;
  }


  public FullWorkflowRequestPortfolioInformationField linkToPortfolioField(Boolean linkToPortfolioField) {
    this.linkToPortfolioField = linkToPortfolioField;
    return this;
  }

   /**
   * Portfolio link.
   * @return linkToPortfolioField
  **/
  @ApiModelProperty(required = true, value = "Portfolio link.")
  @JsonProperty(JSON_PROPERTY_LINK_TO_PORTFOLIO_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getLinkToPortfolioField() {
    return linkToPortfolioField;
  }


  public void setLinkToPortfolioField(Boolean linkToPortfolioField) {
    this.linkToPortfolioField = linkToPortfolioField;
  }


  public FullWorkflowRequestPortfolioInformationField portfolioIDField(BigDecimal portfolioIDField) {
    this.portfolioIDField = portfolioIDField;
    return this;
  }

   /**
   * Portfolio ID.
   * @return portfolioIDField
  **/
  @ApiModelProperty(example = "11112", required = true, value = "Portfolio ID.")
  @JsonProperty(JSON_PROPERTY_PORTFOLIO_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getPortfolioIDField() {
    return portfolioIDField;
  }


  public void setPortfolioIDField(BigDecimal portfolioIDField) {
    this.portfolioIDField = portfolioIDField;
  }


  public FullWorkflowRequestPortfolioInformationField portfolioNameField(String portfolioNameField) {
    this.portfolioNameField = portfolioNameField;
    return this;
  }

   /**
   * Portfolio name.
   * @return portfolioNameField
  **/
  @ApiModelProperty(example = "Portfolio 1", required = true, value = "Portfolio name.")
  @JsonProperty(JSON_PROPERTY_PORTFOLIO_NAME_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPortfolioNameField() {
    return portfolioNameField;
  }


  public void setPortfolioNameField(String portfolioNameField) {
    this.portfolioNameField = portfolioNameField;
  }


  /**
   * Return true if this FullWorkflowRequest_PortfolioInformationField object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullWorkflowRequestPortfolioInformationField fullWorkflowRequestPortfolioInformationField = (FullWorkflowRequestPortfolioInformationField) o;
    return Objects.equals(this.createPortfolioField, fullWorkflowRequestPortfolioInformationField.createPortfolioField) &&
        Objects.equals(this.linkToPortfolioField, fullWorkflowRequestPortfolioInformationField.linkToPortfolioField) &&
        Objects.equals(this.portfolioIDField, fullWorkflowRequestPortfolioInformationField.portfolioIDField) &&
        Objects.equals(this.portfolioNameField, fullWorkflowRequestPortfolioInformationField.portfolioNameField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createPortfolioField, linkToPortfolioField, portfolioIDField, portfolioNameField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullWorkflowRequestPortfolioInformationField {\n");
    sb.append("    createPortfolioField: ").append(toIndentedString(createPortfolioField)).append("\n");
    sb.append("    linkToPortfolioField: ").append(toIndentedString(linkToPortfolioField)).append("\n");
    sb.append("    portfolioIDField: ").append(toIndentedString(portfolioIDField)).append("\n");
    sb.append("    portfolioNameField: ").append(toIndentedString(portfolioNameField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

