/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.SigniFlowup.connect.models.FullWorkflowRequestGroupStepField;
import com.SigniFlowup.connect.models.FullWorkflowRequestWorkflowUserFieldsField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * FullWorkflowRequestWorkflowUsersListField
 */
@JsonPropertyOrder({
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_ACTION_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_ALLOW_PROXY_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_AUTO_SIGN_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_EMAIL_ADDRESS_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_GROUP_STEP_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_LANGUAGE_CODE_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_LATITUDE_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_LONGITUDE_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_MOBILE_NUMBER_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_PRELOADED_FACE_TO_FACE_SIGNERS_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_SIGN_REASON_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_SIGNER_PASSWORD_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_USER_FIRST_NAME_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_USER_FULL_NAME_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_USER_LAST_NAME_FIELD,
  FullWorkflowRequestWorkflowUsersListField.JSON_PROPERTY_WORKFLOW_USER_FIELDS_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FullWorkflowRequestWorkflowUsersListField {
  public static final String JSON_PROPERTY_ACTION_FIELD = "ActionField";
  private BigDecimal actionField;

  public static final String JSON_PROPERTY_ALLOW_PROXY_FIELD = "AllowProxyField";
  private BigDecimal allowProxyField;

  public static final String JSON_PROPERTY_AUTO_SIGN_FIELD = "AutoSignField";
  private Boolean autoSignField;

  public static final String JSON_PROPERTY_EMAIL_ADDRESS_FIELD = "EmailAddressField";
  private String emailAddressField;

  public static final String JSON_PROPERTY_GROUP_STEP_FIELD = "GroupStepField";
  private FullWorkflowRequestGroupStepField groupStepField;

  public static final String JSON_PROPERTY_LANGUAGE_CODE_FIELD = "LanguageCodeField";
  private String languageCodeField;

  public static final String JSON_PROPERTY_LATITUDE_FIELD = "LatitudeField";
  private String latitudeField;

  public static final String JSON_PROPERTY_LONGITUDE_FIELD = "LongitudeField";
  private String longitudeField;

  public static final String JSON_PROPERTY_MOBILE_NUMBER_FIELD = "MobileNumberField";
  private String mobileNumberField;

  public static final String JSON_PROPERTY_PRELOADED_FACE_TO_FACE_SIGNERS_FIELD = "PreloadedFaceToFaceSignersField";
  private Set<Object> preloadedFaceToFaceSignersField = null;

  public static final String JSON_PROPERTY_SIGN_REASON_FIELD = "SignReasonField";
  private String signReasonField;

  public static final String JSON_PROPERTY_SIGNER_PASSWORD_FIELD = "SignerPasswordField";
  private String signerPasswordField;

  public static final String JSON_PROPERTY_USER_FIRST_NAME_FIELD = "UserFirstNameField";
  private String userFirstNameField;

  public static final String JSON_PROPERTY_USER_FULL_NAME_FIELD = "UserFullNameField";
  private String userFullNameField;

  public static final String JSON_PROPERTY_USER_LAST_NAME_FIELD = "UserLastNameField";
  private String userLastNameField;

  public static final String JSON_PROPERTY_WORKFLOW_USER_FIELDS_FIELD = "WorkflowUserFieldsField";
  private Set<FullWorkflowRequestWorkflowUserFieldsField> workflowUserFieldsField = null;


  public FullWorkflowRequestWorkflowUsersListField actionField(BigDecimal actionField) {
    this.actionField = actionField;
    return this;
  }

   /**
   * Refers to the order of signatures from the users.
   * @return actionField
  **/
  @ApiModelProperty(required = true, value = "Refers to the order of signatures from the users.")
  @JsonProperty(JSON_PROPERTY_ACTION_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getActionField() {
    return actionField;
  }


  public void setActionField(BigDecimal actionField) {
    this.actionField = actionField;
  }


  public FullWorkflowRequestWorkflowUsersListField allowProxyField(BigDecimal allowProxyField) {
    this.allowProxyField = allowProxyField;
    return this;
  }

   /**
   * Allow proxy confirmation field.
   * @return allowProxyField
  **/
  @ApiModelProperty(required = true, value = "Allow proxy confirmation field.")
  @JsonProperty(JSON_PROPERTY_ALLOW_PROXY_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getAllowProxyField() {
    return allowProxyField;
  }


  public void setAllowProxyField(BigDecimal allowProxyField) {
    this.allowProxyField = allowProxyField;
  }


  public FullWorkflowRequestWorkflowUsersListField autoSignField(Boolean autoSignField) {
    this.autoSignField = autoSignField;
    return this;
  }

   /**
   * ### Enable auto sign.  &#x60;True &#x3D; Signature will be applied automaticly False &#x3D; User will need to login and Sign&#x60; 
   * @return autoSignField
  **/
  @ApiModelProperty(required = true, value = "### Enable auto sign.  `True = Signature will be applied automaticly False = User will need to login and Sign` ")
  @JsonProperty(JSON_PROPERTY_AUTO_SIGN_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getAutoSignField() {
    return autoSignField;
  }


  public void setAutoSignField(Boolean autoSignField) {
    this.autoSignField = autoSignField;
  }


  public FullWorkflowRequestWorkflowUsersListField emailAddressField(String emailAddressField) {
    this.emailAddressField = emailAddressField;
    return this;
  }

   /**
   * Workflow user&#39;s email addresses.
   * @return emailAddressField
  **/
  @ApiModelProperty(example = "email@domain.com", required = true, value = "Workflow user's email addresses.")
  @JsonProperty(JSON_PROPERTY_EMAIL_ADDRESS_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmailAddressField() {
    return emailAddressField;
  }


  public void setEmailAddressField(String emailAddressField) {
    this.emailAddressField = emailAddressField;
  }


  public FullWorkflowRequestWorkflowUsersListField groupStepField(FullWorkflowRequestGroupStepField groupStepField) {
    this.groupStepField = groupStepField;
    return this;
  }

   /**
   * Get groupStepField
   * @return groupStepField
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GROUP_STEP_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FullWorkflowRequestGroupStepField getGroupStepField() {
    return groupStepField;
  }


  public void setGroupStepField(FullWorkflowRequestGroupStepField groupStepField) {
    this.groupStepField = groupStepField;
  }


  public FullWorkflowRequestWorkflowUsersListField languageCodeField(String languageCodeField) {
    this.languageCodeField = languageCodeField;
    return this;
  }

   /**
   * #### Sets the display language for the user ##### ISO 2 Digit Code  &#x60;en &#x3D; English es &#x3D; Spanish fr &#x3D; French&#x60; 
   * @return languageCodeField
  **/
  @ApiModelProperty(example = "ENG", required = true, value = "#### Sets the display language for the user ##### ISO 2 Digit Code  `en = English es = Spanish fr = French` ")
  @JsonProperty(JSON_PROPERTY_LANGUAGE_CODE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLanguageCodeField() {
    return languageCodeField;
  }


  public void setLanguageCodeField(String languageCodeField) {
    this.languageCodeField = languageCodeField;
  }


  public FullWorkflowRequestWorkflowUsersListField latitudeField(String latitudeField) {
    this.latitudeField = latitudeField;
    return this;
  }

   /**
   * Location latitude.
   * @return latitudeField
  **/
  @ApiModelProperty(required = true, value = "Location latitude.")
  @JsonProperty(JSON_PROPERTY_LATITUDE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLatitudeField() {
    return latitudeField;
  }


  public void setLatitudeField(String latitudeField) {
    this.latitudeField = latitudeField;
  }


  public FullWorkflowRequestWorkflowUsersListField longitudeField(String longitudeField) {
    this.longitudeField = longitudeField;
    return this;
  }

   /**
   * Location longtitude.
   * @return longitudeField
  **/
  @ApiModelProperty(required = true, value = "Location longtitude.")
  @JsonProperty(JSON_PROPERTY_LONGITUDE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLongitudeField() {
    return longitudeField;
  }


  public void setLongitudeField(String longitudeField) {
    this.longitudeField = longitudeField;
  }


  public FullWorkflowRequestWorkflowUsersListField mobileNumberField(String mobileNumberField) {
    this.mobileNumberField = mobileNumberField;
    return this;
  }

   /**
   * Group user&#39;s mobile number.
   * @return mobileNumberField
  **/
  @ApiModelProperty(example = "078 222 2222", required = true, value = "Group user's mobile number.")
  @JsonProperty(JSON_PROPERTY_MOBILE_NUMBER_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMobileNumberField() {
    return mobileNumberField;
  }


  public void setMobileNumberField(String mobileNumberField) {
    this.mobileNumberField = mobileNumberField;
  }


  public FullWorkflowRequestWorkflowUsersListField preloadedFaceToFaceSignersField(Set<Object> preloadedFaceToFaceSignersField) {
    this.preloadedFaceToFaceSignersField = preloadedFaceToFaceSignersField;
    return this;
  }

  public FullWorkflowRequestWorkflowUsersListField addPreloadedFaceToFaceSignersFieldItem(Object preloadedFaceToFaceSignersFieldItem) {
    if (this.preloadedFaceToFaceSignersField == null) {
      this.preloadedFaceToFaceSignersField = new LinkedHashSet<>();
    }
    this.preloadedFaceToFaceSignersField.add(preloadedFaceToFaceSignersFieldItem);
    return this;
  }

   /**
   * Preloaded user&#39;s who will be using the face to face signature field.
   * @return preloadedFaceToFaceSignersField
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Preloaded user's who will be using the face to face signature field.")
  @JsonProperty(JSON_PROPERTY_PRELOADED_FACE_TO_FACE_SIGNERS_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<Object> getPreloadedFaceToFaceSignersField() {
    return preloadedFaceToFaceSignersField;
  }


  public void setPreloadedFaceToFaceSignersField(Set<Object> preloadedFaceToFaceSignersField) {
    this.preloadedFaceToFaceSignersField = preloadedFaceToFaceSignersField;
  }


  public FullWorkflowRequestWorkflowUsersListField signReasonField(String signReasonField) {
    this.signReasonField = signReasonField;
    return this;
  }

   /**
   * Reason for signature.
   * @return signReasonField
  **/
  @ApiModelProperty(example = "Because yes", required = true, value = "Reason for signature.")
  @JsonProperty(JSON_PROPERTY_SIGN_REASON_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignReasonField() {
    return signReasonField;
  }


  public void setSignReasonField(String signReasonField) {
    this.signReasonField = signReasonField;
  }


  public FullWorkflowRequestWorkflowUsersListField signerPasswordField(String signerPasswordField) {
    this.signerPasswordField = signerPasswordField;
    return this;
  }

   /**
   * Face to face user&#39;s password.
   * @return signerPasswordField
  **/
  @ApiModelProperty(example = "P@ssw0rd", required = true, value = "Face to face user's password.")
  @JsonProperty(JSON_PROPERTY_SIGNER_PASSWORD_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignerPasswordField() {
    return signerPasswordField;
  }


  public void setSignerPasswordField(String signerPasswordField) {
    this.signerPasswordField = signerPasswordField;
  }


  public FullWorkflowRequestWorkflowUsersListField userFirstNameField(String userFirstNameField) {
    this.userFirstNameField = userFirstNameField;
    return this;
  }

   /**
   * Face to face user&#39;s first name.
   * @return userFirstNameField
  **/
  @ApiModelProperty(example = "John", required = true, value = "Face to face user's first name.")
  @JsonProperty(JSON_PROPERTY_USER_FIRST_NAME_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserFirstNameField() {
    return userFirstNameField;
  }


  public void setUserFirstNameField(String userFirstNameField) {
    this.userFirstNameField = userFirstNameField;
  }


  public FullWorkflowRequestWorkflowUsersListField userFullNameField(String userFullNameField) {
    this.userFullNameField = userFullNameField;
    return this;
  }

   /**
   * Face to face user&#39;s full name.
   * @return userFullNameField
  **/
  @ApiModelProperty(example = "John Smith", required = true, value = "Face to face user's full name.")
  @JsonProperty(JSON_PROPERTY_USER_FULL_NAME_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserFullNameField() {
    return userFullNameField;
  }


  public void setUserFullNameField(String userFullNameField) {
    this.userFullNameField = userFullNameField;
  }


  public FullWorkflowRequestWorkflowUsersListField userLastNameField(String userLastNameField) {
    this.userLastNameField = userLastNameField;
    return this;
  }

   /**
   * Face to face user&#39;s last name.
   * @return userLastNameField
  **/
  @ApiModelProperty(example = "Smith", required = true, value = "Face to face user's last name.")
  @JsonProperty(JSON_PROPERTY_USER_LAST_NAME_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserLastNameField() {
    return userLastNameField;
  }


  public void setUserLastNameField(String userLastNameField) {
    this.userLastNameField = userLastNameField;
  }


  public FullWorkflowRequestWorkflowUsersListField workflowUserFieldsField(Set<FullWorkflowRequestWorkflowUserFieldsField> workflowUserFieldsField) {
    this.workflowUserFieldsField = workflowUserFieldsField;
    return this;
  }

  public FullWorkflowRequestWorkflowUsersListField addWorkflowUserFieldsFieldItem(FullWorkflowRequestWorkflowUserFieldsField workflowUserFieldsFieldItem) {
    if (this.workflowUserFieldsField == null) {
      this.workflowUserFieldsField = new LinkedHashSet<>();
    }
    this.workflowUserFieldsField.add(workflowUserFieldsFieldItem);
    return this;
  }

   /**
   * The list of the workflowed documents field.
   * @return workflowUserFieldsField
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of the workflowed documents field.")
  @JsonProperty(JSON_PROPERTY_WORKFLOW_USER_FIELDS_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<FullWorkflowRequestWorkflowUserFieldsField> getWorkflowUserFieldsField() {
    return workflowUserFieldsField;
  }


  public void setWorkflowUserFieldsField(Set<FullWorkflowRequestWorkflowUserFieldsField> workflowUserFieldsField) {
    this.workflowUserFieldsField = workflowUserFieldsField;
  }


  /**
   * Return true if this FullWorkflowRequest_WorkflowUsersListField object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullWorkflowRequestWorkflowUsersListField fullWorkflowRequestWorkflowUsersListField = (FullWorkflowRequestWorkflowUsersListField) o;
    return Objects.equals(this.actionField, fullWorkflowRequestWorkflowUsersListField.actionField) &&
        Objects.equals(this.allowProxyField, fullWorkflowRequestWorkflowUsersListField.allowProxyField) &&
        Objects.equals(this.autoSignField, fullWorkflowRequestWorkflowUsersListField.autoSignField) &&
        Objects.equals(this.emailAddressField, fullWorkflowRequestWorkflowUsersListField.emailAddressField) &&
        Objects.equals(this.groupStepField, fullWorkflowRequestWorkflowUsersListField.groupStepField) &&
        Objects.equals(this.languageCodeField, fullWorkflowRequestWorkflowUsersListField.languageCodeField) &&
        Objects.equals(this.latitudeField, fullWorkflowRequestWorkflowUsersListField.latitudeField) &&
        Objects.equals(this.longitudeField, fullWorkflowRequestWorkflowUsersListField.longitudeField) &&
        Objects.equals(this.mobileNumberField, fullWorkflowRequestWorkflowUsersListField.mobileNumberField) &&
        Objects.equals(this.preloadedFaceToFaceSignersField, fullWorkflowRequestWorkflowUsersListField.preloadedFaceToFaceSignersField) &&
        Objects.equals(this.signReasonField, fullWorkflowRequestWorkflowUsersListField.signReasonField) &&
        Objects.equals(this.signerPasswordField, fullWorkflowRequestWorkflowUsersListField.signerPasswordField) &&
        Objects.equals(this.userFirstNameField, fullWorkflowRequestWorkflowUsersListField.userFirstNameField) &&
        Objects.equals(this.userFullNameField, fullWorkflowRequestWorkflowUsersListField.userFullNameField) &&
        Objects.equals(this.userLastNameField, fullWorkflowRequestWorkflowUsersListField.userLastNameField) &&
        Objects.equals(this.workflowUserFieldsField, fullWorkflowRequestWorkflowUsersListField.workflowUserFieldsField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionField, allowProxyField, autoSignField, emailAddressField, groupStepField, languageCodeField, latitudeField, longitudeField, mobileNumberField, preloadedFaceToFaceSignersField, signReasonField, signerPasswordField, userFirstNameField, userFullNameField, userLastNameField, workflowUserFieldsField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullWorkflowRequestWorkflowUsersListField {\n");
    sb.append("    actionField: ").append(toIndentedString(actionField)).append("\n");
    sb.append("    allowProxyField: ").append(toIndentedString(allowProxyField)).append("\n");
    sb.append("    autoSignField: ").append(toIndentedString(autoSignField)).append("\n");
    sb.append("    emailAddressField: ").append(toIndentedString(emailAddressField)).append("\n");
    sb.append("    groupStepField: ").append(toIndentedString(groupStepField)).append("\n");
    sb.append("    languageCodeField: ").append(toIndentedString(languageCodeField)).append("\n");
    sb.append("    latitudeField: ").append(toIndentedString(latitudeField)).append("\n");
    sb.append("    longitudeField: ").append(toIndentedString(longitudeField)).append("\n");
    sb.append("    mobileNumberField: ").append(toIndentedString(mobileNumberField)).append("\n");
    sb.append("    preloadedFaceToFaceSignersField: ").append(toIndentedString(preloadedFaceToFaceSignersField)).append("\n");
    sb.append("    signReasonField: ").append(toIndentedString(signReasonField)).append("\n");
    sb.append("    signerPasswordField: ").append(toIndentedString(signerPasswordField)).append("\n");
    sb.append("    userFirstNameField: ").append(toIndentedString(userFirstNameField)).append("\n");
    sb.append("    userFullNameField: ").append(toIndentedString(userFullNameField)).append("\n");
    sb.append("    userLastNameField: ").append(toIndentedString(userLastNameField)).append("\n");
    sb.append("    workflowUserFieldsField: ").append(toIndentedString(workflowUserFieldsField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

