/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * #### This is the response returned when a document url is requested.
 */
@ApiModel(description = "#### This is the response returned when a document url is requested.")
@JsonPropertyOrder({
  GetDocLinkResponse.JSON_PROPERTY_RESULT,
  GetDocLinkResponse.JSON_PROPERTY_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetDocLinkResponse {
  public static final String JSON_PROPERTY_RESULT = "Result";
  private String result;

  public static final String JSON_PROPERTY_URL = "Url";
  private String url;


  public GetDocLinkResponse result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Displays the result of the call.
   * @return result
  **/
  @ApiModelProperty(required = true, value = "Displays the result of the call.")
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResult() {
    return result;
  }


  public void setResult(String result) {
    this.result = result;
  }


  public GetDocLinkResponse url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL
   * @return url
  **/
  @ApiModelProperty(required = true, value = "URL")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  /**
   * Return true if this GetDocLinkResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDocLinkResponse getDocLinkResponse = (GetDocLinkResponse) o;
    return Objects.equals(this.result, getDocLinkResponse.result) &&
        Objects.equals(this.url, getDocLinkResponse.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDocLinkResponse {\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

