/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.SigniFlowup.connect.models.GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * #### The response returned after requesting the document tag field ox position.
 */
@ApiModel(description = "#### The response returned after requesting the document tag field ox position.")
@JsonPropertyOrder({
  GetDocumentTagFieldBoxPositionResponse.JSON_PROPERTY_DOCUMENT_TAG_FIELDS_BOX_POSITION_FIELD,
  GetDocumentTagFieldBoxPositionResponse.JSON_PROPERTY_RESULT_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetDocumentTagFieldBoxPositionResponse {
  public static final String JSON_PROPERTY_DOCUMENT_TAG_FIELDS_BOX_POSITION_FIELD = "DocumentTagFieldsBoxPositionField";
  private GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField documentTagFieldsBoxPositionField;

  public static final String JSON_PROPERTY_RESULT_FIELD = "ResultField";
  private String resultField;


  public GetDocumentTagFieldBoxPositionResponse documentTagFieldsBoxPositionField(GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField documentTagFieldsBoxPositionField) {
    this.documentTagFieldsBoxPositionField = documentTagFieldsBoxPositionField;
    return this;
  }

   /**
   * Get documentTagFieldsBoxPositionField
   * @return documentTagFieldsBoxPositionField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DOCUMENT_TAG_FIELDS_BOX_POSITION_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField getDocumentTagFieldsBoxPositionField() {
    return documentTagFieldsBoxPositionField;
  }


  public void setDocumentTagFieldsBoxPositionField(GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField documentTagFieldsBoxPositionField) {
    this.documentTagFieldsBoxPositionField = documentTagFieldsBoxPositionField;
  }


  public GetDocumentTagFieldBoxPositionResponse resultField(String resultField) {
    this.resultField = resultField;
    return this;
  }

   /**
   * Displays the result of the call.
   * @return resultField
  **/
  @ApiModelProperty(required = true, value = "Displays the result of the call.")
  @JsonProperty(JSON_PROPERTY_RESULT_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResultField() {
    return resultField;
  }


  public void setResultField(String resultField) {
    this.resultField = resultField;
  }


  /**
   * Return true if this GetDocumentTagFieldBoxPositionResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDocumentTagFieldBoxPositionResponse getDocumentTagFieldBoxPositionResponse = (GetDocumentTagFieldBoxPositionResponse) o;
    return Objects.equals(this.documentTagFieldsBoxPositionField, getDocumentTagFieldBoxPositionResponse.documentTagFieldsBoxPositionField) &&
        Objects.equals(this.resultField, getDocumentTagFieldBoxPositionResponse.resultField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentTagFieldsBoxPositionField, resultField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDocumentTagFieldBoxPositionResponse {\n");
    sb.append("    documentTagFieldsBoxPositionField: ").append(toIndentedString(documentTagFieldsBoxPositionField)).append("\n");
    sb.append("    resultField: ").append(toIndentedString(resultField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

