/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * GetDocumentAuditResponseActivityField
 */
@JsonPropertyOrder({
  GetDocumentAuditResponseActivityField.JSON_PROPERTY_ACTION_ORDER_FIELD,
  GetDocumentAuditResponseActivityField.JSON_PROPERTY_ADDITIONAL_FIELD,
  GetDocumentAuditResponseActivityField.JSON_PROPERTY_DOC_I_D_FIELD,
  GetDocumentAuditResponseActivityField.JSON_PROPERTY_EMAIL_FIELD,
  GetDocumentAuditResponseActivityField.JSON_PROPERTY_EVENT_DATE_FIELD,
  GetDocumentAuditResponseActivityField.JSON_PROPERTY_EVENT_FIELD,
  GetDocumentAuditResponseActivityField.JSON_PROPERTY_EVENT_STATUS_FIELD,
  GetDocumentAuditResponseActivityField.JSON_PROPERTY_LOCATION_FIELD,
  GetDocumentAuditResponseActivityField.JSON_PROPERTY_ORDER_DATE_FIELD,
  GetDocumentAuditResponseActivityField.JSON_PROPERTY_PAGE_FIELD,
  GetDocumentAuditResponseActivityField.JSON_PROPERTY_USER_FULL_NAME_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetDocumentAuditResponseActivityField {
  public static final String JSON_PROPERTY_ACTION_ORDER_FIELD = "ActionOrderField";
  private String actionOrderField;

  public static final String JSON_PROPERTY_ADDITIONAL_FIELD = "AdditionalField";
  private String additionalField;

  public static final String JSON_PROPERTY_DOC_I_D_FIELD = "DocIDField";
  private String docIDField;

  public static final String JSON_PROPERTY_EMAIL_FIELD = "EmailField";
  private String emailField;

  public static final String JSON_PROPERTY_EVENT_DATE_FIELD = "EventDateField";
  private String eventDateField;

  public static final String JSON_PROPERTY_EVENT_FIELD = "EventField";
  private String eventField;

  public static final String JSON_PROPERTY_EVENT_STATUS_FIELD = "EventStatusField";
  private String eventStatusField;

  public static final String JSON_PROPERTY_LOCATION_FIELD = "LocationField";
  private String locationField;

  public static final String JSON_PROPERTY_ORDER_DATE_FIELD = "OrderDateField";
  private String orderDateField;

  public static final String JSON_PROPERTY_PAGE_FIELD = "PageField";
  private String pageField;

  public static final String JSON_PROPERTY_USER_FULL_NAME_FIELD = "UserFullNameField";
  private String userFullNameField;


  public GetDocumentAuditResponseActivityField actionOrderField(String actionOrderField) {
    this.actionOrderField = actionOrderField;
    return this;
  }

   /**
   * Get actionOrderField
   * @return actionOrderField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ACTION_ORDER_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getActionOrderField() {
    return actionOrderField;
  }


  public void setActionOrderField(String actionOrderField) {
    this.actionOrderField = actionOrderField;
  }


  public GetDocumentAuditResponseActivityField additionalField(String additionalField) {
    this.additionalField = additionalField;
    return this;
  }

   /**
   * Get additionalField
   * @return additionalField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAdditionalField() {
    return additionalField;
  }


  public void setAdditionalField(String additionalField) {
    this.additionalField = additionalField;
  }


  public GetDocumentAuditResponseActivityField docIDField(String docIDField) {
    this.docIDField = docIDField;
    return this;
  }

   /**
   * Get docIDField
   * @return docIDField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DOC_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDocIDField() {
    return docIDField;
  }


  public void setDocIDField(String docIDField) {
    this.docIDField = docIDField;
  }


  public GetDocumentAuditResponseActivityField emailField(String emailField) {
    this.emailField = emailField;
    return this;
  }

   /**
   * The user&#39;s email.
   * @return emailField
  **/
  @ApiModelProperty(example = "email@domain.com", required = true, value = "The user's email.")
  @JsonProperty(JSON_PROPERTY_EMAIL_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmailField() {
    return emailField;
  }


  public void setEmailField(String emailField) {
    this.emailField = emailField;
  }


  public GetDocumentAuditResponseActivityField eventDateField(String eventDateField) {
    this.eventDateField = eventDateField;
    return this;
  }

   /**
   * Get eventDateField
   * @return eventDateField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_EVENT_DATE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEventDateField() {
    return eventDateField;
  }


  public void setEventDateField(String eventDateField) {
    this.eventDateField = eventDateField;
  }


  public GetDocumentAuditResponseActivityField eventField(String eventField) {
    this.eventField = eventField;
    return this;
  }

   /**
   * Get eventField
   * @return eventField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_EVENT_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEventField() {
    return eventField;
  }


  public void setEventField(String eventField) {
    this.eventField = eventField;
  }


  public GetDocumentAuditResponseActivityField eventStatusField(String eventStatusField) {
    this.eventStatusField = eventStatusField;
    return this;
  }

   /**
   * Get eventStatusField
   * @return eventStatusField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_EVENT_STATUS_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEventStatusField() {
    return eventStatusField;
  }


  public void setEventStatusField(String eventStatusField) {
    this.eventStatusField = eventStatusField;
  }


  public GetDocumentAuditResponseActivityField locationField(String locationField) {
    this.locationField = locationField;
    return this;
  }

   /**
   * Get locationField
   * @return locationField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOCATION_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLocationField() {
    return locationField;
  }


  public void setLocationField(String locationField) {
    this.locationField = locationField;
  }


  public GetDocumentAuditResponseActivityField orderDateField(String orderDateField) {
    this.orderDateField = orderDateField;
    return this;
  }

   /**
   * Get orderDateField
   * @return orderDateField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ORDER_DATE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrderDateField() {
    return orderDateField;
  }


  public void setOrderDateField(String orderDateField) {
    this.orderDateField = orderDateField;
  }


  public GetDocumentAuditResponseActivityField pageField(String pageField) {
    this.pageField = pageField;
    return this;
  }

   /**
   * Get pageField
   * @return pageField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PAGE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPageField() {
    return pageField;
  }


  public void setPageField(String pageField) {
    this.pageField = pageField;
  }


  public GetDocumentAuditResponseActivityField userFullNameField(String userFullNameField) {
    this.userFullNameField = userFullNameField;
    return this;
  }

   /**
   * User&#39;s full name.
   * @return userFullNameField
  **/
  @ApiModelProperty(required = true, value = "User's full name.")
  @JsonProperty(JSON_PROPERTY_USER_FULL_NAME_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserFullNameField() {
    return userFullNameField;
  }


  public void setUserFullNameField(String userFullNameField) {
    this.userFullNameField = userFullNameField;
  }


  /**
   * Return true if this GetDocumentAuditResponse_ActivityField object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDocumentAuditResponseActivityField getDocumentAuditResponseActivityField = (GetDocumentAuditResponseActivityField) o;
    return Objects.equals(this.actionOrderField, getDocumentAuditResponseActivityField.actionOrderField) &&
        Objects.equals(this.additionalField, getDocumentAuditResponseActivityField.additionalField) &&
        Objects.equals(this.docIDField, getDocumentAuditResponseActivityField.docIDField) &&
        Objects.equals(this.emailField, getDocumentAuditResponseActivityField.emailField) &&
        Objects.equals(this.eventDateField, getDocumentAuditResponseActivityField.eventDateField) &&
        Objects.equals(this.eventField, getDocumentAuditResponseActivityField.eventField) &&
        Objects.equals(this.eventStatusField, getDocumentAuditResponseActivityField.eventStatusField) &&
        Objects.equals(this.locationField, getDocumentAuditResponseActivityField.locationField) &&
        Objects.equals(this.orderDateField, getDocumentAuditResponseActivityField.orderDateField) &&
        Objects.equals(this.pageField, getDocumentAuditResponseActivityField.pageField) &&
        Objects.equals(this.userFullNameField, getDocumentAuditResponseActivityField.userFullNameField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionOrderField, additionalField, docIDField, emailField, eventDateField, eventField, eventStatusField, locationField, orderDateField, pageField, userFullNameField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDocumentAuditResponseActivityField {\n");
    sb.append("    actionOrderField: ").append(toIndentedString(actionOrderField)).append("\n");
    sb.append("    additionalField: ").append(toIndentedString(additionalField)).append("\n");
    sb.append("    docIDField: ").append(toIndentedString(docIDField)).append("\n");
    sb.append("    emailField: ").append(toIndentedString(emailField)).append("\n");
    sb.append("    eventDateField: ").append(toIndentedString(eventDateField)).append("\n");
    sb.append("    eventField: ").append(toIndentedString(eventField)).append("\n");
    sb.append("    eventStatusField: ").append(toIndentedString(eventStatusField)).append("\n");
    sb.append("    locationField: ").append(toIndentedString(locationField)).append("\n");
    sb.append("    orderDateField: ").append(toIndentedString(orderDateField)).append("\n");
    sb.append("    pageField: ").append(toIndentedString(pageField)).append("\n");
    sb.append("    userFullNameField: ").append(toIndentedString(userFullNameField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

