/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.SigniFlowup.connect.models.GetPrepperTemplateResponsePrepperTemplateValuesField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * #### The response received after requesting a document template.
 */
@ApiModel(description = "#### The response received after requesting a document template.")
@JsonPropertyOrder({
  GetPrepperTemplateResponse.JSON_PROPERTY_PREPPER_TEMPLATE_VALUES_FIELD,
  GetPrepperTemplateResponse.JSON_PROPERTY_RESULT_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetPrepperTemplateResponse {
  public static final String JSON_PROPERTY_PREPPER_TEMPLATE_VALUES_FIELD = "PrepperTemplateValuesField";
  private Set<GetPrepperTemplateResponsePrepperTemplateValuesField> prepperTemplateValuesField = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_RESULT_FIELD = "ResultField";
  private String resultField;


  public GetPrepperTemplateResponse prepperTemplateValuesField(Set<GetPrepperTemplateResponsePrepperTemplateValuesField> prepperTemplateValuesField) {
    this.prepperTemplateValuesField = prepperTemplateValuesField;
    return this;
  }

  public GetPrepperTemplateResponse addPrepperTemplateValuesFieldItem(GetPrepperTemplateResponsePrepperTemplateValuesField prepperTemplateValuesFieldItem) {
    this.prepperTemplateValuesField.add(prepperTemplateValuesFieldItem);
    return this;
  }

   /**
   * Get prepperTemplateValuesField
   * @return prepperTemplateValuesField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PREPPER_TEMPLATE_VALUES_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Set<GetPrepperTemplateResponsePrepperTemplateValuesField> getPrepperTemplateValuesField() {
    return prepperTemplateValuesField;
  }


  public void setPrepperTemplateValuesField(Set<GetPrepperTemplateResponsePrepperTemplateValuesField> prepperTemplateValuesField) {
    this.prepperTemplateValuesField = prepperTemplateValuesField;
  }


  public GetPrepperTemplateResponse resultField(String resultField) {
    this.resultField = resultField;
    return this;
  }

   /**
   * Displays the result of the call.
   * @return resultField
  **/
  @ApiModelProperty(required = true, value = "Displays the result of the call.")
  @JsonProperty(JSON_PROPERTY_RESULT_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResultField() {
    return resultField;
  }


  public void setResultField(String resultField) {
    this.resultField = resultField;
  }


  /**
   * Return true if this GetPrepperTemplateResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPrepperTemplateResponse getPrepperTemplateResponse = (GetPrepperTemplateResponse) o;
    return Objects.equals(this.prepperTemplateValuesField, getPrepperTemplateResponse.prepperTemplateValuesField) &&
        Objects.equals(this.resultField, getPrepperTemplateResponse.resultField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prepperTemplateValuesField, resultField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPrepperTemplateResponse {\n");
    sb.append("    prepperTemplateValuesField: ").append(toIndentedString(prepperTemplateValuesField)).append("\n");
    sb.append("    resultField: ").append(toIndentedString(resultField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

