/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.SigniFlowup.connect.models.GetPrepperTemplateListResponseTemplateInformationValuesField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * #### The response returned when the document template list gets requested.
 */
@ApiModel(description = "#### The response returned when the document template list gets requested.")
@JsonPropertyOrder({
  GetPrepperTemplateListResponse.JSON_PROPERTY_RESULT_FIELD,
  GetPrepperTemplateListResponse.JSON_PROPERTY_TEMPLATE_INFORMATION_VALUES_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetPrepperTemplateListResponse {
  public static final String JSON_PROPERTY_RESULT_FIELD = "ResultField";
  private String resultField;

  public static final String JSON_PROPERTY_TEMPLATE_INFORMATION_VALUES_FIELD = "TemplateInformationValuesField";
  private Set<GetPrepperTemplateListResponseTemplateInformationValuesField> templateInformationValuesField = new LinkedHashSet<>();


  public GetPrepperTemplateListResponse resultField(String resultField) {
    this.resultField = resultField;
    return this;
  }

   /**
   * Displays the result of the call.
   * @return resultField
  **/
  @ApiModelProperty(required = true, value = "Displays the result of the call.")
  @JsonProperty(JSON_PROPERTY_RESULT_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResultField() {
    return resultField;
  }


  public void setResultField(String resultField) {
    this.resultField = resultField;
  }


  public GetPrepperTemplateListResponse templateInformationValuesField(Set<GetPrepperTemplateListResponseTemplateInformationValuesField> templateInformationValuesField) {
    this.templateInformationValuesField = templateInformationValuesField;
    return this;
  }

  public GetPrepperTemplateListResponse addTemplateInformationValuesFieldItem(GetPrepperTemplateListResponseTemplateInformationValuesField templateInformationValuesFieldItem) {
    this.templateInformationValuesField.add(templateInformationValuesFieldItem);
    return this;
  }

   /**
   * Get templateInformationValuesField
   * @return templateInformationValuesField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TEMPLATE_INFORMATION_VALUES_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Set<GetPrepperTemplateListResponseTemplateInformationValuesField> getTemplateInformationValuesField() {
    return templateInformationValuesField;
  }


  public void setTemplateInformationValuesField(Set<GetPrepperTemplateListResponseTemplateInformationValuesField> templateInformationValuesField) {
    this.templateInformationValuesField = templateInformationValuesField;
  }


  /**
   * Return true if this GetPrepperTemplateListResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPrepperTemplateListResponse getPrepperTemplateListResponse = (GetPrepperTemplateListResponse) o;
    return Objects.equals(this.resultField, getPrepperTemplateListResponse.resultField) &&
        Objects.equals(this.templateInformationValuesField, getPrepperTemplateListResponse.templateInformationValuesField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultField, templateInformationValuesField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPrepperTemplateListResponse {\n");
    sb.append("    resultField: ").append(toIndentedString(resultField)).append("\n");
    sb.append("    templateInformationValuesField: ").append(toIndentedString(templateInformationValuesField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

