/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * GetPrepperTemplateResponsePrepperTemplateValuesField
 */
@JsonPropertyOrder({
  GetPrepperTemplateResponsePrepperTemplateValuesField.JSON_PROPERTY_COLOR_FIELD,
  GetPrepperTemplateResponsePrepperTemplateValuesField.JSON_PROPERTY_DOC_FIELD_I_D_FIELD,
  GetPrepperTemplateResponsePrepperTemplateValuesField.JSON_PROPERTY_DOC_I_D_FIELD,
  GetPrepperTemplateResponsePrepperTemplateValuesField.JSON_PROPERTY_FIELD_TYPE_FIELD,
  GetPrepperTemplateResponsePrepperTemplateValuesField.JSON_PROPERTY_HEIGHT_FIELD,
  GetPrepperTemplateResponsePrepperTemplateValuesField.JSON_PROPERTY_PAGE_NUMBER_FIELD,
  GetPrepperTemplateResponsePrepperTemplateValuesField.JSON_PROPERTY_USER_FULL_NAME_FIELD,
  GetPrepperTemplateResponsePrepperTemplateValuesField.JSON_PROPERTY_USER_I_D_FIELD,
  GetPrepperTemplateResponsePrepperTemplateValuesField.JSON_PROPERTY_VALUE_FIELD,
  GetPrepperTemplateResponsePrepperTemplateValuesField.JSON_PROPERTY_WIDTH_FIELD,
  GetPrepperTemplateResponsePrepperTemplateValuesField.JSON_PROPERTY_XCOORDINATE_FIELD,
  GetPrepperTemplateResponsePrepperTemplateValuesField.JSON_PROPERTY_YCOORDINATE_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetPrepperTemplateResponsePrepperTemplateValuesField {
  public static final String JSON_PROPERTY_COLOR_FIELD = "ColorField";
  private String colorField;

  public static final String JSON_PROPERTY_DOC_FIELD_I_D_FIELD = "DocFieldIDField";
  private String docFieldIDField;

  public static final String JSON_PROPERTY_DOC_I_D_FIELD = "DocIDField";
  private BigDecimal docIDField;

  public static final String JSON_PROPERTY_FIELD_TYPE_FIELD = "FieldTypeField";
  private String fieldTypeField;

  public static final String JSON_PROPERTY_HEIGHT_FIELD = "HeightField";
  private BigDecimal heightField;

  public static final String JSON_PROPERTY_PAGE_NUMBER_FIELD = "PageNumberField";
  private BigDecimal pageNumberField;

  public static final String JSON_PROPERTY_USER_FULL_NAME_FIELD = "UserFullNameField";
  private String userFullNameField;

  public static final String JSON_PROPERTY_USER_I_D_FIELD = "UserIDField";
  private BigDecimal userIDField;

  public static final String JSON_PROPERTY_VALUE_FIELD = "ValueField";
  private String valueField;

  public static final String JSON_PROPERTY_WIDTH_FIELD = "WidthField";
  private BigDecimal widthField;

  public static final String JSON_PROPERTY_XCOORDINATE_FIELD = "XCoordinateField";
  private BigDecimal xcoordinateField;

  public static final String JSON_PROPERTY_YCOORDINATE_FIELD = "YCoordinateField";
  private BigDecimal ycoordinateField;


  public GetPrepperTemplateResponsePrepperTemplateValuesField colorField(String colorField) {
    this.colorField = colorField;
    return this;
  }

   /**
   * Get colorField
   * @return colorField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COLOR_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getColorField() {
    return colorField;
  }


  public void setColorField(String colorField) {
    this.colorField = colorField;
  }


  public GetPrepperTemplateResponsePrepperTemplateValuesField docFieldIDField(String docFieldIDField) {
    this.docFieldIDField = docFieldIDField;
    return this;
  }

   /**
   * Get docFieldIDField
   * @return docFieldIDField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DOC_FIELD_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDocFieldIDField() {
    return docFieldIDField;
  }


  public void setDocFieldIDField(String docFieldIDField) {
    this.docFieldIDField = docFieldIDField;
  }


  public GetPrepperTemplateResponsePrepperTemplateValuesField docIDField(BigDecimal docIDField) {
    this.docIDField = docIDField;
    return this;
  }

   /**
   * Get docIDField
   * @return docIDField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DOC_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getDocIDField() {
    return docIDField;
  }


  public void setDocIDField(BigDecimal docIDField) {
    this.docIDField = docIDField;
  }


  public GetPrepperTemplateResponsePrepperTemplateValuesField fieldTypeField(String fieldTypeField) {
    this.fieldTypeField = fieldTypeField;
    return this;
  }

   /**
   * Get fieldTypeField
   * @return fieldTypeField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FIELD_TYPE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFieldTypeField() {
    return fieldTypeField;
  }


  public void setFieldTypeField(String fieldTypeField) {
    this.fieldTypeField = fieldTypeField;
  }


  public GetPrepperTemplateResponsePrepperTemplateValuesField heightField(BigDecimal heightField) {
    this.heightField = heightField;
    return this;
  }

   /**
   * Field height.
   * @return heightField
  **/
  @ApiModelProperty(required = true, value = "Field height.")
  @JsonProperty(JSON_PROPERTY_HEIGHT_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getHeightField() {
    return heightField;
  }


  public void setHeightField(BigDecimal heightField) {
    this.heightField = heightField;
  }


  public GetPrepperTemplateResponsePrepperTemplateValuesField pageNumberField(BigDecimal pageNumberField) {
    this.pageNumberField = pageNumberField;
    return this;
  }

   /**
   * Get pageNumberField
   * @return pageNumberField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PAGE_NUMBER_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getPageNumberField() {
    return pageNumberField;
  }


  public void setPageNumberField(BigDecimal pageNumberField) {
    this.pageNumberField = pageNumberField;
  }


  public GetPrepperTemplateResponsePrepperTemplateValuesField userFullNameField(String userFullNameField) {
    this.userFullNameField = userFullNameField;
    return this;
  }

   /**
   * The user&#39;s full name.
   * @return userFullNameField
  **/
  @ApiModelProperty(required = true, value = "The user's full name.")
  @JsonProperty(JSON_PROPERTY_USER_FULL_NAME_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserFullNameField() {
    return userFullNameField;
  }


  public void setUserFullNameField(String userFullNameField) {
    this.userFullNameField = userFullNameField;
  }


  public GetPrepperTemplateResponsePrepperTemplateValuesField userIDField(BigDecimal userIDField) {
    this.userIDField = userIDField;
    return this;
  }

   /**
   * The user&#39;s ID.
   * @return userIDField
  **/
  @ApiModelProperty(required = true, value = "The user's ID.")
  @JsonProperty(JSON_PROPERTY_USER_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getUserIDField() {
    return userIDField;
  }


  public void setUserIDField(BigDecimal userIDField) {
    this.userIDField = userIDField;
  }


  public GetPrepperTemplateResponsePrepperTemplateValuesField valueField(String valueField) {
    this.valueField = valueField;
    return this;
  }

   /**
   * Get valueField
   * @return valueField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VALUE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getValueField() {
    return valueField;
  }


  public void setValueField(String valueField) {
    this.valueField = valueField;
  }


  public GetPrepperTemplateResponsePrepperTemplateValuesField widthField(BigDecimal widthField) {
    this.widthField = widthField;
    return this;
  }

   /**
   * Field width.
   * @return widthField
  **/
  @ApiModelProperty(required = true, value = "Field width.")
  @JsonProperty(JSON_PROPERTY_WIDTH_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getWidthField() {
    return widthField;
  }


  public void setWidthField(BigDecimal widthField) {
    this.widthField = widthField;
  }


  public GetPrepperTemplateResponsePrepperTemplateValuesField xcoordinateField(BigDecimal xcoordinateField) {
    this.xcoordinateField = xcoordinateField;
    return this;
  }

   /**
   * The x coordinates of the fields.
   * @return xcoordinateField
  **/
  @ApiModelProperty(required = true, value = "The x coordinates of the fields.")
  @JsonProperty(JSON_PROPERTY_XCOORDINATE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getXcoordinateField() {
    return xcoordinateField;
  }


  public void setXcoordinateField(BigDecimal xcoordinateField) {
    this.xcoordinateField = xcoordinateField;
  }


  public GetPrepperTemplateResponsePrepperTemplateValuesField ycoordinateField(BigDecimal ycoordinateField) {
    this.ycoordinateField = ycoordinateField;
    return this;
  }

   /**
   * The y coordinates of the fields
   * @return ycoordinateField
  **/
  @ApiModelProperty(required = true, value = "The y coordinates of the fields")
  @JsonProperty(JSON_PROPERTY_YCOORDINATE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getYcoordinateField() {
    return ycoordinateField;
  }


  public void setYcoordinateField(BigDecimal ycoordinateField) {
    this.ycoordinateField = ycoordinateField;
  }


  /**
   * Return true if this GetPrepperTemplateResponse_PrepperTemplateValuesField object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPrepperTemplateResponsePrepperTemplateValuesField getPrepperTemplateResponsePrepperTemplateValuesField = (GetPrepperTemplateResponsePrepperTemplateValuesField) o;
    return Objects.equals(this.colorField, getPrepperTemplateResponsePrepperTemplateValuesField.colorField) &&
        Objects.equals(this.docFieldIDField, getPrepperTemplateResponsePrepperTemplateValuesField.docFieldIDField) &&
        Objects.equals(this.docIDField, getPrepperTemplateResponsePrepperTemplateValuesField.docIDField) &&
        Objects.equals(this.fieldTypeField, getPrepperTemplateResponsePrepperTemplateValuesField.fieldTypeField) &&
        Objects.equals(this.heightField, getPrepperTemplateResponsePrepperTemplateValuesField.heightField) &&
        Objects.equals(this.pageNumberField, getPrepperTemplateResponsePrepperTemplateValuesField.pageNumberField) &&
        Objects.equals(this.userFullNameField, getPrepperTemplateResponsePrepperTemplateValuesField.userFullNameField) &&
        Objects.equals(this.userIDField, getPrepperTemplateResponsePrepperTemplateValuesField.userIDField) &&
        Objects.equals(this.valueField, getPrepperTemplateResponsePrepperTemplateValuesField.valueField) &&
        Objects.equals(this.widthField, getPrepperTemplateResponsePrepperTemplateValuesField.widthField) &&
        Objects.equals(this.xcoordinateField, getPrepperTemplateResponsePrepperTemplateValuesField.xcoordinateField) &&
        Objects.equals(this.ycoordinateField, getPrepperTemplateResponsePrepperTemplateValuesField.ycoordinateField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(colorField, docFieldIDField, docIDField, fieldTypeField, heightField, pageNumberField, userFullNameField, userIDField, valueField, widthField, xcoordinateField, ycoordinateField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPrepperTemplateResponsePrepperTemplateValuesField {\n");
    sb.append("    colorField: ").append(toIndentedString(colorField)).append("\n");
    sb.append("    docFieldIDField: ").append(toIndentedString(docFieldIDField)).append("\n");
    sb.append("    docIDField: ").append(toIndentedString(docIDField)).append("\n");
    sb.append("    fieldTypeField: ").append(toIndentedString(fieldTypeField)).append("\n");
    sb.append("    heightField: ").append(toIndentedString(heightField)).append("\n");
    sb.append("    pageNumberField: ").append(toIndentedString(pageNumberField)).append("\n");
    sb.append("    userFullNameField: ").append(toIndentedString(userFullNameField)).append("\n");
    sb.append("    userIDField: ").append(toIndentedString(userIDField)).append("\n");
    sb.append("    valueField: ").append(toIndentedString(valueField)).append("\n");
    sb.append("    widthField: ").append(toIndentedString(widthField)).append("\n");
    sb.append("    xcoordinateField: ").append(toIndentedString(xcoordinateField)).append("\n");
    sb.append("    ycoordinateField: ").append(toIndentedString(ycoordinateField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

