/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.SigniFlowup.connect.models.TokenField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * #### This request is used to get the url link to a portfolio.
 */
@ApiModel(description = "#### This request is used to get the url link to a portfolio.")
@JsonPropertyOrder({
  LinkToPortfolioRequest.JSON_PROPERTY_DOC_I_D_FIELD,
  LinkToPortfolioRequest.JSON_PROPERTY_DOCUMENT_NAME_FIELD,
  LinkToPortfolioRequest.JSON_PROPERTY_PORTFOLIO_I_D_FIELD,
  LinkToPortfolioRequest.JSON_PROPERTY_TOKEN_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LinkToPortfolioRequest {
  public static final String JSON_PROPERTY_DOC_I_D_FIELD = "DocIDField";
  private String docIDField;

  public static final String JSON_PROPERTY_DOCUMENT_NAME_FIELD = "DocumentNameField";
  private String documentNameField;

  public static final String JSON_PROPERTY_PORTFOLIO_I_D_FIELD = "PortfolioIDField";
  private String portfolioIDField;

  public static final String JSON_PROPERTY_TOKEN_FIELD = "TokenField";
  private TokenField tokenField;


  public LinkToPortfolioRequest docIDField(String docIDField) {
    this.docIDField = docIDField;
    return this;
  }

   /**
   * The document ID.
   * @return docIDField
  **/
  @ApiModelProperty(required = true, value = "The document ID.")
  @JsonProperty(JSON_PROPERTY_DOC_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDocIDField() {
    return docIDField;
  }


  public void setDocIDField(String docIDField) {
    this.docIDField = docIDField;
  }


  public LinkToPortfolioRequest documentNameField(String documentNameField) {
    this.documentNameField = documentNameField;
    return this;
  }

   /**
   * Document name.
   * @return documentNameField
  **/
  @ApiModelProperty(required = true, value = "Document name.")
  @JsonProperty(JSON_PROPERTY_DOCUMENT_NAME_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDocumentNameField() {
    return documentNameField;
  }


  public void setDocumentNameField(String documentNameField) {
    this.documentNameField = documentNameField;
  }


  public LinkToPortfolioRequest portfolioIDField(String portfolioIDField) {
    this.portfolioIDField = portfolioIDField;
    return this;
  }

   /**
   * The portfolio ID.
   * @return portfolioIDField
  **/
  @ApiModelProperty(required = true, value = "The portfolio ID.")
  @JsonProperty(JSON_PROPERTY_PORTFOLIO_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPortfolioIDField() {
    return portfolioIDField;
  }


  public void setPortfolioIDField(String portfolioIDField) {
    this.portfolioIDField = portfolioIDField;
  }


  public LinkToPortfolioRequest tokenField(TokenField tokenField) {
    this.tokenField = tokenField;
    return this;
  }

   /**
   * Get tokenField
   * @return tokenField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOKEN_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TokenField getTokenField() {
    return tokenField;
  }


  public void setTokenField(TokenField tokenField) {
    this.tokenField = tokenField;
  }


  /**
   * Return true if this LinkToPortfolioRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkToPortfolioRequest linkToPortfolioRequest = (LinkToPortfolioRequest) o;
    return Objects.equals(this.docIDField, linkToPortfolioRequest.docIDField) &&
        Objects.equals(this.documentNameField, linkToPortfolioRequest.documentNameField) &&
        Objects.equals(this.portfolioIDField, linkToPortfolioRequest.portfolioIDField) &&
        Objects.equals(this.tokenField, linkToPortfolioRequest.tokenField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docIDField, documentNameField, portfolioIDField, tokenField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkToPortfolioRequest {\n");
    sb.append("    docIDField: ").append(toIndentedString(docIDField)).append("\n");
    sb.append("    documentNameField: ").append(toIndentedString(documentNameField)).append("\n");
    sb.append("    portfolioIDField: ").append(toIndentedString(portfolioIDField)).append("\n");
    sb.append("    tokenField: ").append(toIndentedString(tokenField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

