/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * #### The request sent when a user Logs in.
 */
@ApiModel(description = "#### The request sent when a user Logs in.")
@JsonPropertyOrder({
  LoginRequest.JSON_PROPERTY_USER_NAME_FIELD,
  LoginRequest.JSON_PROPERTY_PASSWORD_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LoginRequest {
  public static final String JSON_PROPERTY_USER_NAME_FIELD = "UserNameField";
  private String userNameField;

  public static final String JSON_PROPERTY_PASSWORD_FIELD = "PasswordField";
  private String passwordField;


  public LoginRequest userNameField(String userNameField) {
    this.userNameField = userNameField;
    return this;
  }

   /**
   * Email address of the user generating a Token
   * @return userNameField
  **/
  @ApiModelProperty(example = "email@domain.com", required = true, value = "Email address of the user generating a Token")
  @JsonProperty(JSON_PROPERTY_USER_NAME_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserNameField() {
    return userNameField;
  }


  public void setUserNameField(String userNameField) {
    this.userNameField = userNameField;
  }


  public LoginRequest passwordField(String passwordField) {
    this.passwordField = passwordField;
    return this;
  }

   /**
   * SigniFlow user password
   * @return passwordField
  **/
  @ApiModelProperty(example = "Password", required = true, value = "SigniFlow user password")
  @JsonProperty(JSON_PROPERTY_PASSWORD_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPasswordField() {
    return passwordField;
  }


  public void setPasswordField(String passwordField) {
    this.passwordField = passwordField;
  }


  /**
   * Return true if this LoginRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginRequest loginRequest = (LoginRequest) o;
    return Objects.equals(this.userNameField, loginRequest.userNameField) &&
        Objects.equals(this.passwordField, loginRequest.passwordField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userNameField, passwordField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginRequest {\n");
    sb.append("    userNameField: ").append(toIndentedString(userNameField)).append("\n");
    sb.append("    passwordField: ").append(toIndentedString(passwordField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

