/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * MultipleSignersSigningCeremonyRequestSignerListField
 */
@JsonPropertyOrder({
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNATURE_H_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNATURE_IMAGE_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNATURE_IMAGE_INCLUDE_BORDER_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNATURE_IMAGE_INCLUDE_REASON_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNATURE_IMAGE_INCLUDE_SIGNED_BY_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNATURE_IMAGE_INCLUDE_SIGNED_DATE_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNATURE_IMAGE_TYPE_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNATURE_PAGE_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNATURE_W_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNATURE_X_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNATURE_Y_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNER_EMAIL_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNER_FULL_NAME_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNER_INDENTIFICATION_NUMBER_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNER_LOCATION_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNER_MOBILE_NUMBER_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNER_REASON_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNER_TRUST_ORIGIN_FIELD,
  MultipleSignersSigningCeremonyRequestSignerListField.JSON_PROPERTY_SIGNER_TRUST_REFERENCE_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MultipleSignersSigningCeremonyRequestSignerListField {
  public static final String JSON_PROPERTY_SIGNATURE_H_FIELD = "SignatureHField";
  private BigDecimal signatureHField;

  public static final String JSON_PROPERTY_SIGNATURE_IMAGE_FIELD = "SignatureImageField";
  private String signatureImageField;

  public static final String JSON_PROPERTY_SIGNATURE_IMAGE_INCLUDE_BORDER_FIELD = "SignatureImageIncludeBorderField";
  private Boolean signatureImageIncludeBorderField;

  public static final String JSON_PROPERTY_SIGNATURE_IMAGE_INCLUDE_REASON_FIELD = "SignatureImageIncludeReasonField";
  private Boolean signatureImageIncludeReasonField;

  public static final String JSON_PROPERTY_SIGNATURE_IMAGE_INCLUDE_SIGNED_BY_FIELD = "SignatureImageIncludeSignedByField";
  private Boolean signatureImageIncludeSignedByField;

  public static final String JSON_PROPERTY_SIGNATURE_IMAGE_INCLUDE_SIGNED_DATE_FIELD = "SignatureImageIncludeSignedDateField";
  private Boolean signatureImageIncludeSignedDateField;

  public static final String JSON_PROPERTY_SIGNATURE_IMAGE_TYPE_FIELD = "SignatureImageTypeField";
  private BigDecimal signatureImageTypeField;

  public static final String JSON_PROPERTY_SIGNATURE_PAGE_FIELD = "SignaturePageField";
  private BigDecimal signaturePageField;

  public static final String JSON_PROPERTY_SIGNATURE_W_FIELD = "SignatureWField";
  private BigDecimal signatureWField;

  public static final String JSON_PROPERTY_SIGNATURE_X_FIELD = "SignatureXField";
  private BigDecimal signatureXField;

  public static final String JSON_PROPERTY_SIGNATURE_Y_FIELD = "SignatureYField";
  private BigDecimal signatureYField;

  public static final String JSON_PROPERTY_SIGNER_EMAIL_FIELD = "SignerEmailField";
  private String signerEmailField;

  public static final String JSON_PROPERTY_SIGNER_FULL_NAME_FIELD = "SignerFullNameField";
  private String signerFullNameField;

  public static final String JSON_PROPERTY_SIGNER_INDENTIFICATION_NUMBER_FIELD = "SignerIndentificationNumberField";
  private String signerIndentificationNumberField;

  public static final String JSON_PROPERTY_SIGNER_LOCATION_FIELD = "SignerLocationField";
  private String signerLocationField;

  public static final String JSON_PROPERTY_SIGNER_MOBILE_NUMBER_FIELD = "SignerMobileNumberField";
  private String signerMobileNumberField;

  public static final String JSON_PROPERTY_SIGNER_REASON_FIELD = "SignerReasonField";
  private String signerReasonField;

  public static final String JSON_PROPERTY_SIGNER_TRUST_ORIGIN_FIELD = "SignerTrustOriginField";
  private String signerTrustOriginField;

  public static final String JSON_PROPERTY_SIGNER_TRUST_REFERENCE_FIELD = "SignerTrustReferenceField";
  private String signerTrustReferenceField;


  public MultipleSignersSigningCeremonyRequestSignerListField signatureHField(BigDecimal signatureHField) {
    this.signatureHField = signatureHField;
    return this;
  }

   /**
   * Get signatureHField
   * @return signatureHField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_H_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getSignatureHField() {
    return signatureHField;
  }


  public void setSignatureHField(BigDecimal signatureHField) {
    this.signatureHField = signatureHField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signatureImageField(String signatureImageField) {
    this.signatureImageField = signatureImageField;
    return this;
  }

   /**
   * Get signatureImageField
   * @return signatureImageField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_IMAGE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignatureImageField() {
    return signatureImageField;
  }


  public void setSignatureImageField(String signatureImageField) {
    this.signatureImageField = signatureImageField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signatureImageIncludeBorderField(Boolean signatureImageIncludeBorderField) {
    this.signatureImageIncludeBorderField = signatureImageIncludeBorderField;
    return this;
  }

   /**
   * Get signatureImageIncludeBorderField
   * @return signatureImageIncludeBorderField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_IMAGE_INCLUDE_BORDER_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getSignatureImageIncludeBorderField() {
    return signatureImageIncludeBorderField;
  }


  public void setSignatureImageIncludeBorderField(Boolean signatureImageIncludeBorderField) {
    this.signatureImageIncludeBorderField = signatureImageIncludeBorderField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signatureImageIncludeReasonField(Boolean signatureImageIncludeReasonField) {
    this.signatureImageIncludeReasonField = signatureImageIncludeReasonField;
    return this;
  }

   /**
   * Get signatureImageIncludeReasonField
   * @return signatureImageIncludeReasonField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_IMAGE_INCLUDE_REASON_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getSignatureImageIncludeReasonField() {
    return signatureImageIncludeReasonField;
  }


  public void setSignatureImageIncludeReasonField(Boolean signatureImageIncludeReasonField) {
    this.signatureImageIncludeReasonField = signatureImageIncludeReasonField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signatureImageIncludeSignedByField(Boolean signatureImageIncludeSignedByField) {
    this.signatureImageIncludeSignedByField = signatureImageIncludeSignedByField;
    return this;
  }

   /**
   * Get signatureImageIncludeSignedByField
   * @return signatureImageIncludeSignedByField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_IMAGE_INCLUDE_SIGNED_BY_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getSignatureImageIncludeSignedByField() {
    return signatureImageIncludeSignedByField;
  }


  public void setSignatureImageIncludeSignedByField(Boolean signatureImageIncludeSignedByField) {
    this.signatureImageIncludeSignedByField = signatureImageIncludeSignedByField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signatureImageIncludeSignedDateField(Boolean signatureImageIncludeSignedDateField) {
    this.signatureImageIncludeSignedDateField = signatureImageIncludeSignedDateField;
    return this;
  }

   /**
   * Get signatureImageIncludeSignedDateField
   * @return signatureImageIncludeSignedDateField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_IMAGE_INCLUDE_SIGNED_DATE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getSignatureImageIncludeSignedDateField() {
    return signatureImageIncludeSignedDateField;
  }


  public void setSignatureImageIncludeSignedDateField(Boolean signatureImageIncludeSignedDateField) {
    this.signatureImageIncludeSignedDateField = signatureImageIncludeSignedDateField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signatureImageTypeField(BigDecimal signatureImageTypeField) {
    this.signatureImageTypeField = signatureImageTypeField;
    return this;
  }

   /**
   * Get signatureImageTypeField
   * @return signatureImageTypeField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_IMAGE_TYPE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getSignatureImageTypeField() {
    return signatureImageTypeField;
  }


  public void setSignatureImageTypeField(BigDecimal signatureImageTypeField) {
    this.signatureImageTypeField = signatureImageTypeField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signaturePageField(BigDecimal signaturePageField) {
    this.signaturePageField = signaturePageField;
    return this;
  }

   /**
   * Get signaturePageField
   * @return signaturePageField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_PAGE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getSignaturePageField() {
    return signaturePageField;
  }


  public void setSignaturePageField(BigDecimal signaturePageField) {
    this.signaturePageField = signaturePageField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signatureWField(BigDecimal signatureWField) {
    this.signatureWField = signatureWField;
    return this;
  }

   /**
   * Get signatureWField
   * @return signatureWField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_W_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getSignatureWField() {
    return signatureWField;
  }


  public void setSignatureWField(BigDecimal signatureWField) {
    this.signatureWField = signatureWField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signatureXField(BigDecimal signatureXField) {
    this.signatureXField = signatureXField;
    return this;
  }

   /**
   * Get signatureXField
   * @return signatureXField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_X_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getSignatureXField() {
    return signatureXField;
  }


  public void setSignatureXField(BigDecimal signatureXField) {
    this.signatureXField = signatureXField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signatureYField(BigDecimal signatureYField) {
    this.signatureYField = signatureYField;
    return this;
  }

   /**
   * Get signatureYField
   * @return signatureYField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_Y_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getSignatureYField() {
    return signatureYField;
  }


  public void setSignatureYField(BigDecimal signatureYField) {
    this.signatureYField = signatureYField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signerEmailField(String signerEmailField) {
    this.signerEmailField = signerEmailField;
    return this;
  }

   /**
   * Get signerEmailField
   * @return signerEmailField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNER_EMAIL_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignerEmailField() {
    return signerEmailField;
  }


  public void setSignerEmailField(String signerEmailField) {
    this.signerEmailField = signerEmailField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signerFullNameField(String signerFullNameField) {
    this.signerFullNameField = signerFullNameField;
    return this;
  }

   /**
   * Get signerFullNameField
   * @return signerFullNameField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNER_FULL_NAME_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignerFullNameField() {
    return signerFullNameField;
  }


  public void setSignerFullNameField(String signerFullNameField) {
    this.signerFullNameField = signerFullNameField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signerIndentificationNumberField(String signerIndentificationNumberField) {
    this.signerIndentificationNumberField = signerIndentificationNumberField;
    return this;
  }

   /**
   * Get signerIndentificationNumberField
   * @return signerIndentificationNumberField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNER_INDENTIFICATION_NUMBER_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignerIndentificationNumberField() {
    return signerIndentificationNumberField;
  }


  public void setSignerIndentificationNumberField(String signerIndentificationNumberField) {
    this.signerIndentificationNumberField = signerIndentificationNumberField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signerLocationField(String signerLocationField) {
    this.signerLocationField = signerLocationField;
    return this;
  }

   /**
   * Get signerLocationField
   * @return signerLocationField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNER_LOCATION_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignerLocationField() {
    return signerLocationField;
  }


  public void setSignerLocationField(String signerLocationField) {
    this.signerLocationField = signerLocationField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signerMobileNumberField(String signerMobileNumberField) {
    this.signerMobileNumberField = signerMobileNumberField;
    return this;
  }

   /**
   * Get signerMobileNumberField
   * @return signerMobileNumberField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNER_MOBILE_NUMBER_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignerMobileNumberField() {
    return signerMobileNumberField;
  }


  public void setSignerMobileNumberField(String signerMobileNumberField) {
    this.signerMobileNumberField = signerMobileNumberField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signerReasonField(String signerReasonField) {
    this.signerReasonField = signerReasonField;
    return this;
  }

   /**
   * Get signerReasonField
   * @return signerReasonField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNER_REASON_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignerReasonField() {
    return signerReasonField;
  }


  public void setSignerReasonField(String signerReasonField) {
    this.signerReasonField = signerReasonField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signerTrustOriginField(String signerTrustOriginField) {
    this.signerTrustOriginField = signerTrustOriginField;
    return this;
  }

   /**
   * Get signerTrustOriginField
   * @return signerTrustOriginField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNER_TRUST_ORIGIN_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignerTrustOriginField() {
    return signerTrustOriginField;
  }


  public void setSignerTrustOriginField(String signerTrustOriginField) {
    this.signerTrustOriginField = signerTrustOriginField;
  }


  public MultipleSignersSigningCeremonyRequestSignerListField signerTrustReferenceField(String signerTrustReferenceField) {
    this.signerTrustReferenceField = signerTrustReferenceField;
    return this;
  }

   /**
   * Get signerTrustReferenceField
   * @return signerTrustReferenceField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNER_TRUST_REFERENCE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignerTrustReferenceField() {
    return signerTrustReferenceField;
  }


  public void setSignerTrustReferenceField(String signerTrustReferenceField) {
    this.signerTrustReferenceField = signerTrustReferenceField;
  }


  /**
   * Return true if this MultipleSignersSigningCeremonyRequest_SignerListField object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultipleSignersSigningCeremonyRequestSignerListField multipleSignersSigningCeremonyRequestSignerListField = (MultipleSignersSigningCeremonyRequestSignerListField) o;
    return Objects.equals(this.signatureHField, multipleSignersSigningCeremonyRequestSignerListField.signatureHField) &&
        Objects.equals(this.signatureImageField, multipleSignersSigningCeremonyRequestSignerListField.signatureImageField) &&
        Objects.equals(this.signatureImageIncludeBorderField, multipleSignersSigningCeremonyRequestSignerListField.signatureImageIncludeBorderField) &&
        Objects.equals(this.signatureImageIncludeReasonField, multipleSignersSigningCeremonyRequestSignerListField.signatureImageIncludeReasonField) &&
        Objects.equals(this.signatureImageIncludeSignedByField, multipleSignersSigningCeremonyRequestSignerListField.signatureImageIncludeSignedByField) &&
        Objects.equals(this.signatureImageIncludeSignedDateField, multipleSignersSigningCeremonyRequestSignerListField.signatureImageIncludeSignedDateField) &&
        Objects.equals(this.signatureImageTypeField, multipleSignersSigningCeremonyRequestSignerListField.signatureImageTypeField) &&
        Objects.equals(this.signaturePageField, multipleSignersSigningCeremonyRequestSignerListField.signaturePageField) &&
        Objects.equals(this.signatureWField, multipleSignersSigningCeremonyRequestSignerListField.signatureWField) &&
        Objects.equals(this.signatureXField, multipleSignersSigningCeremonyRequestSignerListField.signatureXField) &&
        Objects.equals(this.signatureYField, multipleSignersSigningCeremonyRequestSignerListField.signatureYField) &&
        Objects.equals(this.signerEmailField, multipleSignersSigningCeremonyRequestSignerListField.signerEmailField) &&
        Objects.equals(this.signerFullNameField, multipleSignersSigningCeremonyRequestSignerListField.signerFullNameField) &&
        Objects.equals(this.signerIndentificationNumberField, multipleSignersSigningCeremonyRequestSignerListField.signerIndentificationNumberField) &&
        Objects.equals(this.signerLocationField, multipleSignersSigningCeremonyRequestSignerListField.signerLocationField) &&
        Objects.equals(this.signerMobileNumberField, multipleSignersSigningCeremonyRequestSignerListField.signerMobileNumberField) &&
        Objects.equals(this.signerReasonField, multipleSignersSigningCeremonyRequestSignerListField.signerReasonField) &&
        Objects.equals(this.signerTrustOriginField, multipleSignersSigningCeremonyRequestSignerListField.signerTrustOriginField) &&
        Objects.equals(this.signerTrustReferenceField, multipleSignersSigningCeremonyRequestSignerListField.signerTrustReferenceField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signatureHField, signatureImageField, signatureImageIncludeBorderField, signatureImageIncludeReasonField, signatureImageIncludeSignedByField, signatureImageIncludeSignedDateField, signatureImageTypeField, signaturePageField, signatureWField, signatureXField, signatureYField, signerEmailField, signerFullNameField, signerIndentificationNumberField, signerLocationField, signerMobileNumberField, signerReasonField, signerTrustOriginField, signerTrustReferenceField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultipleSignersSigningCeremonyRequestSignerListField {\n");
    sb.append("    signatureHField: ").append(toIndentedString(signatureHField)).append("\n");
    sb.append("    signatureImageField: ").append(toIndentedString(signatureImageField)).append("\n");
    sb.append("    signatureImageIncludeBorderField: ").append(toIndentedString(signatureImageIncludeBorderField)).append("\n");
    sb.append("    signatureImageIncludeReasonField: ").append(toIndentedString(signatureImageIncludeReasonField)).append("\n");
    sb.append("    signatureImageIncludeSignedByField: ").append(toIndentedString(signatureImageIncludeSignedByField)).append("\n");
    sb.append("    signatureImageIncludeSignedDateField: ").append(toIndentedString(signatureImageIncludeSignedDateField)).append("\n");
    sb.append("    signatureImageTypeField: ").append(toIndentedString(signatureImageTypeField)).append("\n");
    sb.append("    signaturePageField: ").append(toIndentedString(signaturePageField)).append("\n");
    sb.append("    signatureWField: ").append(toIndentedString(signatureWField)).append("\n");
    sb.append("    signatureXField: ").append(toIndentedString(signatureXField)).append("\n");
    sb.append("    signatureYField: ").append(toIndentedString(signatureYField)).append("\n");
    sb.append("    signerEmailField: ").append(toIndentedString(signerEmailField)).append("\n");
    sb.append("    signerFullNameField: ").append(toIndentedString(signerFullNameField)).append("\n");
    sb.append("    signerIndentificationNumberField: ").append(toIndentedString(signerIndentificationNumberField)).append("\n");
    sb.append("    signerLocationField: ").append(toIndentedString(signerLocationField)).append("\n");
    sb.append("    signerMobileNumberField: ").append(toIndentedString(signerMobileNumberField)).append("\n");
    sb.append("    signerReasonField: ").append(toIndentedString(signerReasonField)).append("\n");
    sb.append("    signerTrustOriginField: ").append(toIndentedString(signerTrustOriginField)).append("\n");
    sb.append("    signerTrustReferenceField: ").append(toIndentedString(signerTrustReferenceField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

