/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * #### Authentication Token
 */
@ApiModel(description = "#### Authentication Token")
@JsonPropertyOrder({
  TokenField.JSON_PROPERTY_TOKEN_EXPIRY_FIELD,
  TokenField.JSON_PROPERTY_TOKEN_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TokenField {
  public static final String JSON_PROPERTY_TOKEN_EXPIRY_FIELD = "TokenExpiryField";
  private OffsetDateTime tokenExpiryField;

  public static final String JSON_PROPERTY_TOKEN_FIELD = "TokenField";
  private String tokenField;


  public TokenField tokenExpiryField(OffsetDateTime tokenExpiryField) {
    this.tokenExpiryField = tokenExpiryField;
    return this;
  }

   /**
   * Expiry date of Token
   * @return tokenExpiryField
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Expiry date of Token")
  @JsonProperty(JSON_PROPERTY_TOKEN_EXPIRY_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTokenExpiryField() {
    return tokenExpiryField;
  }


  public void setTokenExpiryField(OffsetDateTime tokenExpiryField) {
    this.tokenExpiryField = tokenExpiryField;
  }


  public TokenField tokenField(String tokenField) {
    this.tokenField = tokenField;
    return this;
  }

   /**
   * User API Token
   * @return tokenField
  **/
  @ApiModelProperty(example = "aaa111", required = true, value = "User API Token")
  @JsonProperty(JSON_PROPERTY_TOKEN_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTokenField() {
    return tokenField;
  }


  public void setTokenField(String tokenField) {
    this.tokenField = tokenField;
  }


  /**
   * Return true if this TokenField object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenField tokenField = (TokenField) o;
    return Objects.equals(this.tokenExpiryField, tokenField.tokenExpiryField) &&
        Objects.equals(this.tokenField, tokenField.tokenField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tokenExpiryField, tokenField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenField {\n");
    sb.append("    tokenExpiryField: ").append(toIndentedString(tokenExpiryField)).append("\n");
    sb.append("    tokenField: ").append(toIndentedString(tokenField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

