/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.SigniFlowup.connect.models.TokenField;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.SigniFlowup.connect.JSON;


/**
 * #### This request is sent when a document workflow needs to be signed.
 */
@ApiModel(description = "#### This request is sent when a document workflow needs to be signed.")
@JsonPropertyOrder({
  WorkflowSignRequest.JSON_PROPERTY_DOC_I_D_FIELD,
  WorkflowSignRequest.JSON_PROPERTY_LATITUDE_FIELD,
  WorkflowSignRequest.JSON_PROPERTY_LOGIN_PASSWORD_FIELD,
  WorkflowSignRequest.JSON_PROPERTY_LOGIN_USER_NAME_FIELD,
  WorkflowSignRequest.JSON_PROPERTY_LONGITUDE_FIELD,
  WorkflowSignRequest.JSON_PROPERTY_SIGN_REASON_FIELD,
  WorkflowSignRequest.JSON_PROPERTY_TIME_ZONE_OFFSET_FIELD,
  WorkflowSignRequest.JSON_PROPERTY_TOKEN_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WorkflowSignRequest {
  public static final String JSON_PROPERTY_DOC_I_D_FIELD = "DocIDField";
  private String docIDField;

  public static final String JSON_PROPERTY_LATITUDE_FIELD = "LatitudeField";
  private String latitudeField;

  public static final String JSON_PROPERTY_LOGIN_PASSWORD_FIELD = "LoginPasswordField";
  private String loginPasswordField;

  public static final String JSON_PROPERTY_LOGIN_USER_NAME_FIELD = "LoginUserNameField";
  private String loginUserNameField;

  public static final String JSON_PROPERTY_LONGITUDE_FIELD = "LongitudeField";
  private String longitudeField;

  public static final String JSON_PROPERTY_SIGN_REASON_FIELD = "SignReasonField";
  private String signReasonField;

  public static final String JSON_PROPERTY_TIME_ZONE_OFFSET_FIELD = "TimeZoneOffsetField";
  private BigDecimal timeZoneOffsetField;

  public static final String JSON_PROPERTY_TOKEN_FIELD = "TokenField";
  private TokenField tokenField;


  public WorkflowSignRequest docIDField(String docIDField) {
    this.docIDField = docIDField;
    return this;
  }

   /**
   * Get docIDField
   * @return docIDField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DOC_I_D_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDocIDField() {
    return docIDField;
  }


  public void setDocIDField(String docIDField) {
    this.docIDField = docIDField;
  }


  public WorkflowSignRequest latitudeField(String latitudeField) {
    this.latitudeField = latitudeField;
    return this;
  }

   /**
   * Get latitudeField
   * @return latitudeField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LATITUDE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLatitudeField() {
    return latitudeField;
  }


  public void setLatitudeField(String latitudeField) {
    this.latitudeField = latitudeField;
  }


  public WorkflowSignRequest loginPasswordField(String loginPasswordField) {
    this.loginPasswordField = loginPasswordField;
    return this;
  }

   /**
   * Get loginPasswordField
   * @return loginPasswordField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOGIN_PASSWORD_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoginPasswordField() {
    return loginPasswordField;
  }


  public void setLoginPasswordField(String loginPasswordField) {
    this.loginPasswordField = loginPasswordField;
  }


  public WorkflowSignRequest loginUserNameField(String loginUserNameField) {
    this.loginUserNameField = loginUserNameField;
    return this;
  }

   /**
   * Get loginUserNameField
   * @return loginUserNameField
  **/
  @ApiModelProperty(example = "email@domain.com", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOGIN_USER_NAME_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoginUserNameField() {
    return loginUserNameField;
  }


  public void setLoginUserNameField(String loginUserNameField) {
    this.loginUserNameField = loginUserNameField;
  }


  public WorkflowSignRequest longitudeField(String longitudeField) {
    this.longitudeField = longitudeField;
    return this;
  }

   /**
   * Get longitudeField
   * @return longitudeField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LONGITUDE_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLongitudeField() {
    return longitudeField;
  }


  public void setLongitudeField(String longitudeField) {
    this.longitudeField = longitudeField;
  }


  public WorkflowSignRequest signReasonField(String signReasonField) {
    this.signReasonField = signReasonField;
    return this;
  }

   /**
   * Get signReasonField
   * @return signReasonField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGN_REASON_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignReasonField() {
    return signReasonField;
  }


  public void setSignReasonField(String signReasonField) {
    this.signReasonField = signReasonField;
  }


  public WorkflowSignRequest timeZoneOffsetField(BigDecimal timeZoneOffsetField) {
    this.timeZoneOffsetField = timeZoneOffsetField;
    return this;
  }

   /**
   * Get timeZoneOffsetField
   * @return timeZoneOffsetField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TIME_ZONE_OFFSET_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getTimeZoneOffsetField() {
    return timeZoneOffsetField;
  }


  public void setTimeZoneOffsetField(BigDecimal timeZoneOffsetField) {
    this.timeZoneOffsetField = timeZoneOffsetField;
  }


  public WorkflowSignRequest tokenField(TokenField tokenField) {
    this.tokenField = tokenField;
    return this;
  }

   /**
   * Get tokenField
   * @return tokenField
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOKEN_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TokenField getTokenField() {
    return tokenField;
  }


  public void setTokenField(TokenField tokenField) {
    this.tokenField = tokenField;
  }


  /**
   * Return true if this WorkflowSignRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowSignRequest workflowSignRequest = (WorkflowSignRequest) o;
    return Objects.equals(this.docIDField, workflowSignRequest.docIDField) &&
        Objects.equals(this.latitudeField, workflowSignRequest.latitudeField) &&
        Objects.equals(this.loginPasswordField, workflowSignRequest.loginPasswordField) &&
        Objects.equals(this.loginUserNameField, workflowSignRequest.loginUserNameField) &&
        Objects.equals(this.longitudeField, workflowSignRequest.longitudeField) &&
        Objects.equals(this.signReasonField, workflowSignRequest.signReasonField) &&
        Objects.equals(this.timeZoneOffsetField, workflowSignRequest.timeZoneOffsetField) &&
        Objects.equals(this.tokenField, workflowSignRequest.tokenField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docIDField, latitudeField, loginPasswordField, loginUserNameField, longitudeField, signReasonField, timeZoneOffsetField, tokenField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowSignRequest {\n");
    sb.append("    docIDField: ").append(toIndentedString(docIDField)).append("\n");
    sb.append("    latitudeField: ").append(toIndentedString(latitudeField)).append("\n");
    sb.append("    loginPasswordField: ").append(toIndentedString(loginPasswordField)).append("\n");
    sb.append("    loginUserNameField: ").append(toIndentedString(loginUserNameField)).append("\n");
    sb.append("    longitudeField: ").append(toIndentedString(longitudeField)).append("\n");
    sb.append("    signReasonField: ").append(toIndentedString(signReasonField)).append("\n");
    sb.append("    timeZoneOffsetField: ").append(toIndentedString(timeZoneOffsetField)).append("\n");
    sb.append("    tokenField: ").append(toIndentedString(tokenField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

