/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.api;

import com.SigniFlowup.connect.*;
import com.SigniFlowup.connect.auth.*;
import com.SigniFlowup.connect.models.GetAuditDocumentRequest;
import com.SigniFlowup.connect.models.GetAuditDocumentResponse;
import com.SigniFlowup.connect.models.GetDocumentAuditRequest;
import com.SigniFlowup.connect.models.GetDocumentAuditResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuditsApi
 */
public class AuditsApiTest {

    private final AuditsApi api = new AuditsApi();

    /**
     * Get Audit Document
     *
     * #### Used to get an audit document.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postGetAuditDocumentTest() throws ApiException {
        //String contentType = null;
        //GetAuditDocumentRequest getAuditDocumentRequest = null;
        //GetAuditDocumentResponse response = api.postGetAuditDocument(contentType, getAuditDocumentRequest);
        // TODO: test validations
    }

    /**
     * Get Document Audit
     *
     * #### Used to get the audit information from a document.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postGetDocumentAuditTest() throws ApiException {
        //String contentType = null;
        //GetDocumentAuditRequest getDocumentAuditRequest = null;
        //GetDocumentAuditResponse response = api.postGetDocumentAudit(contentType, getDocumentAuditRequest);
        // TODO: test validations
    }

}
