/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.api;

import com.SigniFlowup.connect.*;
import com.SigniFlowup.connect.auth.*;
import com.SigniFlowup.connect.models.MultipleSignersSigningCeremonyRequest;
import com.SigniFlowup.connect.models.MultipleSignersSigningCeremonyResponse;
import com.SigniFlowup.connect.models.SigningCeremonyV2Request;
import com.SigniFlowup.connect.models.SigningCeremonyV2Response;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SigningCeremonyApi
 */
public class SigningCeremonyApiTest {

    private final SigningCeremonyApi api = new SigningCeremonyApi();

    /**
     * Multiple Signers Signing Ceremony
     *
     * #### Used when there are multiple signers on a document.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postMultipleSignersSigningCeremonyTest() throws ApiException {
        //String contentType = null;
        //MultipleSignersSigningCeremonyRequest multipleSignersSigningCeremonyRequest = null;
        //MultipleSignersSigningCeremonyResponse response = api.postMultipleSignersSigningCeremony(contentType, multipleSignersSigningCeremonyRequest);
        // TODO: test validations
    }

    /**
     * Signing Ceremony V2
     *
     * #### Used to initiate the signing process of a document.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postSigningCeremonyV2Test() throws ApiException {
        //String contentType = null;
        //SigningCeremonyV2Request signingCeremonyV2Request = null;
        //SigningCeremonyV2Response response = api.postSigningCeremonyV2(contentType, signingCeremonyV2Request);
        // TODO: test validations
    }

}
