/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.api;

import com.SigniFlowup.connect.*;
import com.SigniFlowup.connect.auth.*;
import com.SigniFlowup.connect.models.ApplyPrepperTemplateRequest;
import com.SigniFlowup.connect.models.ApplyPrepperTemplateResponse;
import com.SigniFlowup.connect.models.GetDocumentTagFieldBoxPositionRequest;
import com.SigniFlowup.connect.models.GetDocumentTagFieldBoxPositionResponse;
import com.SigniFlowup.connect.models.GetDocumentTagFieldPositionRequest;
import com.SigniFlowup.connect.models.GetDocumentTagFieldPositionResponse;
import com.SigniFlowup.connect.models.GetPrepperTemplateListRequest;
import com.SigniFlowup.connect.models.GetPrepperTemplateListResponse;
import com.SigniFlowup.connect.models.GetPrepperTemplateRequest;
import com.SigniFlowup.connect.models.GetPrepperTemplateResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TemplatesApi
 */
public class TemplatesApiTest {

    private final TemplatesApi api = new TemplatesApi();

    /**
     * Apply a Prepper template
     *
     * #### Used when applying a templaet to a document.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postApplyPrepperTemplateTest() throws ApiException {
        //String contentType = null;
        //ApplyPrepperTemplateRequest applyPrepperTemplateRequest = null;
        //ApplyPrepperTemplateResponse response = api.postApplyPrepperTemplate(contentType, applyPrepperTemplateRequest);
        // TODO: test validations
    }

    /**
     * Get Document Tag Field Box Position
     *
     * #### Used to get the tag field box position on a document.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postGetDocumentTagFieldBoxPositionTest() throws ApiException {
        //String contentType = null;
        //GetDocumentTagFieldBoxPositionRequest getDocumentTagFieldBoxPositionRequest = null;
        //GetDocumentTagFieldBoxPositionResponse response = api.postGetDocumentTagFieldBoxPosition(contentType, getDocumentTagFieldBoxPositionRequest);
        // TODO: test validations
    }

    /**
     * Get Document Tag Field Position
     *
     * #### Used to get the tag position on a document.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postGetDocumentTagFieldPositionTest() throws ApiException {
        //String contentType = null;
        //GetDocumentTagFieldPositionRequest getDocumentTagFieldPositionRequest = null;
        //GetDocumentTagFieldPositionResponse response = api.postGetDocumentTagFieldPosition(contentType, getDocumentTagFieldPositionRequest);
        // TODO: test validations
    }

    /**
     * Get Prepper Template
     *
     * #### Used to get a document template.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postGetPrepperTemplateTest() throws ApiException {
        //String contentType = null;
        //GetPrepperTemplateRequest getPrepperTemplateRequest = null;
        //GetPrepperTemplateResponse response = api.postGetPrepperTemplate(contentType, getPrepperTemplateRequest);
        // TODO: test validations
    }

    /**
     * Get Prepper Template List
     *
     * #### Used to get a list of document templates.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postGetPrepperTemplateListTest() throws ApiException {
        //String contentType = null;
        //GetPrepperTemplateListRequest getPrepperTemplateListRequest = null;
        //GetPrepperTemplateListResponse response = api.postGetPrepperTemplateList(contentType, getPrepperTemplateListRequest);
        // TODO: test validations
    }

}
