/*
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.SigniFlowup.connect.api;

import com.SigniFlowup.connect.*;
import com.SigniFlowup.connect.auth.*;
import com.SigniFlowup.connect.models.GetDocLinkRequest;
import com.SigniFlowup.connect.models.GetDocLinkResponse;
import com.SigniFlowup.connect.models.GetDocumentPrepperLinkRequest;
import com.SigniFlowup.connect.models.GetDocumentPrepperLinkResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ViewersApi
 */
public class ViewersApiTest {

    private final ViewersApi api = new ViewersApi();

    /**
     * Get Document Link
     *
     * #### Used to get the document link that will be used to sign a document.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postGetDocLinkTest() throws ApiException {
        //String contentType = null;
        //GetDocLinkRequest getDocLinkRequest = null;
        //GetDocLinkResponse response = api.postGetDocLink(contentType, getDocLinkRequest);
        // TODO: test validations
    }

    /**
     * Get Document Prepper Link
     *
     * #### Used to get a document prepper link (url).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postGetDocumentPrepperLinkTest() throws ApiException {
        //String contentType = null;
        //GetDocumentPrepperLinkRequest getDocumentPrepperLinkRequest = null;
        //GetDocumentPrepperLinkResponse response = api.postGetDocumentPrepperLink(contentType, getDocumentPrepperLinkRequest);
        // TODO: test validations
    }

}
